import {
  databaseRegistrySchema,
  type DatabaseEntry,
} from "@/lib/legacy/admin/architecture/types";

const RAW_DATABASE: DatabaseEntry[] = [
  {
    id: "leads",
    label: "Outreach leads (unified)",
    domain: "product",
    purpose: "SoT outreach unifié — backfill depuis comptable_delivery / comptable / cif; cutover app en cours",
    keyColumns:
      "id, category, segment, email, statut, slug, reservation_link, confirmation_link, profile, client_id, legacy_source_table, legacy_source_id",
    writers: ["admin", "webhook", "cron"],
    readers: ["admin", "cron"],
    profileKeys: "form, communication.delays, display.timeline",
    relatedTables: ["comptable", "cif", "comptable_delivery", "clients"],
    status: "migrated",
  },
  {
    id: "temporary_leads",
    label: "Temporary Instantly import",
    domain: "marketing",
    purpose: "Staging import listes Instantly (streamlit_scraper) — pas le modèle leads unifié",
    keyColumns: "id, email, source_list_id, instantly_payload, migrated_at",
    writers: ["scripts"],
    readers: ["scripts"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "conference_sale_windows",
    label: "Conference sale windows",
    domain: "product",
    purpose: "Toggle on/off for /conference/inscription checkout link",
    keyColumns: "id, status, started_at, ends_at, duration_seconds",
    writers: ["admin", "cron"],
    readers: ["admin", "client", "cron"],
    profileKeys: "—",
    relatedTables: ["payments", "clients"],
    status: "migrated",
  },
  {
    id: "client_appointments",
    label: "Client appointments",
    domain: "product",
    purpose: "RDV livraison on conference client Calendly seats",
    keyColumns:
      "id, client_id, calendly_invitee_uri, status, credited, scheduled_at",
    writers: ["webhook", "client"],
    readers: ["admin", "client"],
    profileKeys: "—",
    relatedTables: ["clients"],
    status: "migrated",
  },
  {
    id: "payments",
    label: "Payments",
    domain: "product",
    purpose: "Paiements Stripe — conférence (client_id) et outreach (lead_id). Idempotence stripe_event_id.",
    keyColumns:
      "id, client_id, lead_id, offer_type, payment_phase, amount_cents, status, stripe_event_id, succeeded_at",
    writers: ["webhook", "admin"],
    readers: ["admin", "client"],
    profileKeys: "—",
    relatedTables: ["leads", "clients"],
    status: "migrated",
  },
  {
    id: "sales_calls",
    label: "Sales calls",
    domain: "product",
    purpose: "Appels commerciaux Calendly — qualification et statut not_paid/paid",
    keyColumns:
      "id, lead_id, email, calendly_invitee_uri, status, forecast_cents, notes",
    writers: ["webhook", "admin"],
    readers: ["admin"],
    profileKeys: "—",
    relatedTables: ["leads"],
    status: "migrated",
  },
  {
    id: "email_sequence_recipients",
    label: "Email sequence recipients",
    domain: "communication",
    purpose: "Management dashboard — enrollment registry per lead/sequence (outreach, booking, client)",
    keyColumns:
      "id, lead_email, lead_category, phase, sequence_slug, provider, status, scheduled_at",
    writers: ["admin", "scripts", "webhook", "cron"],
    readers: ["admin"],
    profileKeys: "—",
    relatedTables: ["booking_email_jobs", "instantly_bypass_pipeline", "comptable", "cif", "comptable_delivery"],
    status: "migrated",
  },
  {
    id: "booking_email_jobs",
    label: "Booking email jobs",
    domain: "communication",
    purpose: "Queue d'envoi emails booking — quand envoyer",
    keyColumns: "id, lead_category, lead_id, email_type, scheduled_for, status",
    writers: ["admin", "webhook", "cron"],
    readers: ["cron", "admin"],
    profileKeys: "communication.delays (source dates)",
    relatedTables: ["comptable", "cif", "comptable_delivery", "booking_email_templates"],
    status: "migrated",
  },
  {
    id: "booking_email_templates",
    label: "Booking email templates",
    domain: "communication",
    purpose: "Corps et sujet des emails booking",
    keyColumns: "id, category, email_type, subject, html_body",
    writers: ["admin"],
    readers: ["cron", "admin"],
    profileKeys: "form.* (variables render)",
    relatedTables: ["booking_email_jobs"],
    status: "migrated",
  },
  {
    id: "niche_outreach_config",
    label: "Niche outreach config",
    domain: "marketing",
    purpose: "Campagne Instantly + event type Calendly par niche (Bookings CRM)",
    keyColumns: "niche, instantly_campaign_id, instantly_list_id, calendly_event_type_uri, updated_at, updated_by",
    writers: ["admin"],
    readers: ["admin", "cron"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "email_variable_bindings",
    label: "Email variable bindings",
    domain: "marketing",
    purpose: "Variables template activées par niche pour éditeurs de séquences",
    keyColumns: "niche, variable_key, enabled, base_url_preview",
    writers: ["admin"],
    readers: ["admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "instantly_bypass_templates",
    label: "Instantly bypass templates",
    domain: "instantly",
    purpose: "Copy E1/E2/E3 interested + no-show",
    keyColumns: "id, step, subject, body",
    writers: ["admin"],
    readers: ["cron", "admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_jobs"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_config",
    label: "Instantly bypass config",
    domain: "instantly",
    purpose: "Subsequence IDs par campagne",
    keyColumns: "campaign_id, subsequence_ids",
    writers: ["admin"],
    readers: ["cron", "webhook", "admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_pipeline"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_events",
    label: "Instantly bypass events",
    domain: "instantly",
    purpose: "Idempotence et audit webhook",
    keyColumns: "id, event_id, campaign_id, email, step",
    writers: ["webhook"],
    readers: ["admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_pipeline"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_jobs",
    label: "Instantly bypass jobs",
    domain: "instantly",
    purpose: "Envois programmés hors heures ouvrées",
    keyColumns: "id, pipeline_id, scheduled_for, status",
    writers: ["webhook", "cron"],
    readers: ["cron", "admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_pipeline"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_pipeline",
    label: "Instantly bypass pipeline",
    domain: "instantly",
    purpose: "Étape courante par lead (step_0…step_3)",
    keyColumns: "id, campaign_id, email, current_step",
    writers: ["webhook", "cron"],
    readers: ["cron", "admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_jobs"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_settings",
    label: "Instantly bypass settings",
    domain: "instantly",
    purpose: "Toggles webhook bypass",
    keyColumns: "key, value",
    writers: ["admin"],
    readers: ["webhook", "admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "deliverability_settings",
    label: "Deliverability settings",
    domain: "instantly",
    purpose: "Seuils alerte, cache refresh, emails exclus (panneau ops)",
    keyColumns: "health_score_warn_below, inbox_rate_warn_below, refresh_minutes, excluded_emails",
    writers: ["admin"],
    readers: ["admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_config",
    label: "AI reply agent config",
    domain: "ai",
    purpose: "Mapping campagne → prompt niche",
    keyColumns: "campaign_id, niche, system_prompt",
    writers: ["admin"],
    readers: ["cron", "webhook", "admin"],
    profileKeys: "—",
    relatedTables: ["ai_reply_agent_messages"],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_messages",
    label: "AI reply agent messages",
    domain: "ai",
    purpose: "Inbound/outbound + statut AI",
    keyColumns: "id, direction, ai_status, latency_ms, knowledge_pack_hash, body",
    writers: ["webhook", "cron"],
    readers: ["admin", "cron"],
    profileKeys: "—",
    relatedTables: ["ai_reply_agent_jobs", "ai_reply_agent_leads"],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_jobs",
    label: "AI reply agent jobs",
    domain: "ai",
    purpose: "Envois différés manuels/auto",
    keyColumns: "id, message_id, scheduled_for, status",
    writers: ["webhook", "cron"],
    readers: ["cron", "admin"],
    profileKeys: "—",
    relatedTables: ["ai_reply_agent_messages"],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_leads",
    label: "AI reply agent leads",
    domain: "ai",
    purpose: "Métadonnées lead pour inbox AI",
    keyColumns: "id, email, campaign_id, niche",
    writers: ["webhook"],
    readers: ["admin", "cron"],
    profileKeys: "—",
    relatedTables: ["ai_reply_agent_messages"],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_blocklist",
    label: "AI reply agent blocklist",
    domain: "ai",
    purpose: "Suppression emails de l'agent",
    keyColumns: "email, reason",
    writers: ["admin"],
    readers: ["webhook", "admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_settings",
    label: "AI reply agent settings",
    domain: "ai",
    purpose: "Toggle webhook global agent",
    keyColumns: "key, value",
    writers: ["admin"],
    readers: ["webhook", "admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
];

export const DATABASE_REGISTRY = databaseRegistrySchema.parse(RAW_DATABASE);

export function getDatabaseRegistry(): DatabaseEntry[] {
  return DATABASE_REGISTRY;
}
