"""Biggy Agency scraper preset — static rules; secrets come from config_loader."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "biggy_agency"
PRESET_LABEL = "Biggy Agency (France)"

BIGGY_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": "52324f4b-22f0-4cde-a033-56dfda5ae6f3",
    "INSTANTLY_CAMPAIGN_ID": "2cd03978-93b3-4462-ad88-f0fb0f35d59c",
    "INSTANTLY_DEDUP_LIST_IDS": [
        "7ef37a12-1c18-4d7a-83c0-8d743ae68412",
        "52324f4b-22f0-4cde-a033-56dfda5ae6f3",
    ],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [
        "57165194-c785-4200-812a-8e8e76da63a9",
        "2cd03978-93b3-4462-ad88-f0fb0f35d59c",
    ],
    "INSTANTLY_PUSH_EVERY": 100,
    "ENRICH_ENABLED": True,
    "ENRICH_BATCH_SIZE": 50,
    "ENRICH_CONCURRENCY": 20,
    "ENRICH_TIMEOUT_MS": 10000,
    "ENRICH_INCLUDED_KEYWORDS": [
        "growth hacking",
        "growth marketing",
        "génération de leads",
        "lead gen",
        "lead generation",
        "acquisition client",
        "a/b testing",
        "cro",
        "conversion rate optimization",
        "optimisation de la conversion",
        "outbound",
        "inbound marketing",
        "marketing automation",
        "scraping",
        "cold email",
        "cold calling",
        "paid traffic",
        "trafic payant",
        "organic traffic",
        "trafic organique",
        "seo",
        "sea",
        "google ads",
        "social ads",
        "facebook ads",
        "marketing digital",
        "webmarketing",
        "publicité en ligne",
        "publicité digitale",
        "stratégie digitale",
        "performance digitale",
        "agence digitale",
        "référencement",
        "référencement naturel",
        "campagnes publicitaires",
        "social media",
        "community management",
        "content marketing",
        "digital marketing",
        "meta ads",
        "linkedin ads",
        "tiktok ads",
        "sem",
        "smo",
        "display",
    ],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [
        "imprimerie",
        "print",
        "flyer",
        "flyers",
        "brochure",
        "carte de visite",
        "bâche",
        "packaging",
        "goodies",
        "objets publicitaires",
    ],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [
        "design graphique",
        "graphisme",
        "création de logo",
        "identité visuelle",
        "branding",
        "relations publiques",
        "relation presse",
    ],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 6,
    "OUTSCRAPER_LIMIT_PER_QUERY": 30,
    "OUTSCRAPER_POLL_INITIAL_S": 45,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 600,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 8,
    "TARGET_LEADS": 5_000,
    "TARGET_MODE": "instantly_pushed",
    "KEYWORDS": [
        "agence de communication",
        "agence communication",
        "agence de publicité",
        "agence publicitaire",
        "agence Google Ads",
        "agence SEA",
        "google ads",
        "agence Facebook ads",
        "meta ads",
        "publicité en ligne",
        "agence de marketing",
        "agence marketing",
        "marketing digital",
        "agence digitale",
        "webmarketing",
        "agence performance",
        "stratégie digitale",
    ],
    "EXPANSION_KEYWORDS": [
        "consultant google ads",
        "agence acquisition",
        "agence inbound marketing",
        "social ads",
        "tiktok ads",
        "agence linkedin ads",
        "agence croissance",
        "growth marketing",
        "agence trafic",
        "media buyer",
        "consultant seo",
        "agence sem",
        "publicité digitale",
        "agence lead gen",
        "performance digitale",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
}

CONFIG = BIGGY_CONFIG
