import {
  componentsRegistrySchema,
  type ComponentEntry,
} from "@/lib/admin/architecture/types";

const RAW_COMPONENTS: ComponentEntry[] = [
  {
    id: "fiche-form",
    name: "Fiche form",
    kind: "component",
    domain: "onboarding_funnel",
    role: "trigger",
    actor: "admin",
    route: "components/internal/funnels/fiche-form.tsx",
    dataIn: "—",
    dataOut: "agence|entreprise row, profile.form, statut=ONBOARDED",
    sideEffects: "Génère slug + URLs tracking",
    storage: "supabase",
    status: "built",
  },
  {
    id: "fiche-form-api",
    name: "Onboarding API",
    kind: "api_route",
    domain: "onboarding_funnel",
    role: "trigger",
    actor: "admin",
    route: "/api/admin/onboarding/[category]",
    dataIn: "Payload formulaire JSON",
    dataOut: "INSERT agence|entreprise, profile JSON",
    sideEffects: "Slug + liens réservation",
    storage: "supabase",
    status: "built",
  },
  {
    id: "funnel-editor",
    name: "Funnel editor",
    kind: "component",
    domain: "sales_funnel",
    role: "edition",
    actor: "admin",
    route: "components/internal/funnels/builder/funnel-editor.tsx",
    dataIn: "content/funnels/{audience}/.../funnel.json",
    dataOut: "funnel.json (steps, layout, presets)",
    sideEffects: "Publish via /api/admin/funnels/[slug]/publish",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "funnel-step-preview",
    name: "Funnel step preview",
    kind: "component",
    domain: "sales_funnel",
    role: "recipient",
    actor: "admin",
    route: "components/internal/funnels/builder/preview-registry.tsx",
    dataIn: "funnel.json step + presets catalog",
    dataOut: "—",
    sideEffects: "—",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "mockup-editor",
    name: "Mockup editor",
    kind: "component",
    domain: "marketing",
    role: "edition",
    actor: "admin",
    route: "components/internal/funnels/mockup-editor.tsx",
    dataIn: "agence_demandes row",
    dataOut: "agence_demandes (titre, visibilité, origine)",
    sideEffects: "Carousel homepage agence",
    storage: "supabase",
    status: "built",
  },
  {
    id: "faq-editor",
    name: "FAQ editor",
    kind: "component",
    domain: "sales_funnel",
    role: "edition",
    actor: "admin",
    route: "components/internal/funnels/faq-editor.tsx",
    dataIn: "doc/tech-stack FAQ markdown",
    dataOut: "FAQ content files",
    sideEffects: "—",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "pricing-editor",
    name: "Pricing editor",
    kind: "component",
    domain: "sales_funnel",
    role: "edition",
    actor: "admin",
    route: "components/internal/funnels/pricing-editor.tsx",
    dataIn: "doc/sop/pricing.md",
    dataOut: "Pricing markdown",
    sideEffects: "—",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "legal-doc",
    name: "Legal doc editor",
    kind: "component",
    domain: "sales_funnel",
    role: "edition",
    actor: "admin",
    route: "components/internal/funnels/legal-doc.tsx",
    dataIn: "doc/tech-stack legal markdown",
    dataOut: "CGV, mentions, confidentialité",
    sideEffects: "—",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "agence-carousel",
    name: "Agence demandes carousel",
    kind: "component",
    domain: "marketing",
    role: "recipient",
    actor: "system",
    route: "components/agence/demandes-carousel.tsx",
    dataIn: "agence_demandes (visible, dates)",
    dataOut: "—",
    sideEffects: "—",
    storage: "supabase",
    status: "built",
  },
  {
    id: "webhook-calendly",
    name: "Calendly webhook",
    kind: "webhook",
    domain: "crm",
    role: "orchestrator",
    actor: "system",
    route: "/api/webhooks/calendly",
    dataIn: "invitee.created|canceled payload",
    dataOut: "statut, calendly_*, scheduled_at",
    sideEffects: "Enqueue booking_email_jobs, sync Instantly",
    storage: "supabase",
    status: "built",
  },
  {
    id: "webhook-instantly",
    name: "Instantly webhook",
    kind: "webhook",
    domain: "crm",
    role: "orchestrator",
    actor: "system",
    route: "/api/webhooks/instantly",
    dataIn: "Instantly event payload",
    dataOut: "instantly_bypass_events, pipeline step",
    sideEffects: "Bypass subsequence sends",
    storage: "supabase",
    status: "built",
  },
  {
    id: "cron-booking-emails",
    name: "Booking emails cron",
    kind: "cron",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "/api/cron/booking-emails",
    dataIn: "booking_email_jobs (due)",
    dataOut: "job status sent|failed",
    sideEffects: "Resend send, engagement tracking",
    storage: "supabase",
    status: "built",
  },
  {
    id: "booking-orchestrator",
    name: "Booking communication orchestrator",
    kind: "orchestrator",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "lib/booking-communication/orchestrator.ts",
    dataIn: "lead row, profile.communication.delays",
    dataOut: "booking_email_jobs inserts",
    sideEffects: "Schedule/cancel emails, send windows Paris",
    storage: "supabase",
    status: "built",
  },
  {
    id: "streamlit-links",
    name: "Streamlit CRM links",
    kind: "component",
    domain: "dashboard_internal",
    role: "trigger",
    actor: "admin",
    route: "app/streamlit_links/app.py",
    dataIn: "agence|entreprise rows",
    dataOut: "statut PATCH via API",
    sideEffects: "Provision links, promote statut",
    storage: "supabase",
    status: "built",
  },
  {
    id: "streamlit-booking-resend",
    name: "Streamlit booking templates",
    kind: "component",
    domain: "dashboard_internal",
    role: "edition",
    actor: "admin",
    route: "app/streamlit_booking_resend/app.py",
    dataIn: "booking_email_templates",
    dataOut: "template HTML/subject",
    sideEffects: "—",
    storage: "supabase",
    status: "built",
  },
  {
    id: "ai-reply-agent-cron",
    name: "AI reply agent cron",
    kind: "cron",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "/api/cron/ai-reply-agent-jobs",
    dataIn: "ai_reply_agent_jobs (due)",
    dataOut: "messages sent, Grok cost",
    sideEffects: "Resend send, Instantly sync",
    storage: "supabase",
    status: "built",
  },
  {
    id: "onboarding-client-form",
    name: "Client onboarding form",
    kind: "component",
    domain: "onboarding_funnel",
    role: "trigger",
    actor: "client",
    route: "app/onboarding/[category]/page.tsx",
    dataIn: "—",
    dataOut: "profile.form, statut=ONBOARDED",
    sideEffects: "—",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "deliverance-timeline",
    name: "Deliverance timeline",
    kind: "component",
    domain: "dashboard_client",
    role: "recipient",
    actor: "client",
    route: "app/suivi/[category]/[slug]/page.tsx",
    dataIn: "profile.display.timeline, deliverance_step",
    dataOut: "—",
    sideEffects: "—",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "post-rdv-survey",
    name: "Post-RDV survey",
    kind: "component",
    domain: "dashboard_client",
    role: "trigger",
    actor: "client",
    route: "app/survey/[token]/page.tsx",
    dataIn: "profile (token validation)",
    dataOut: "profile.survey, statut=SOLD|IN_DELIVERANCE",
    sideEffects: "Enqueue post-survey emails",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "matching-admin-action",
    name: "Mettre en lien (admin)",
    kind: "api_route",
    domain: "dashboard_internal",
    role: "trigger",
    actor: "admin",
    route: "/api/deliverance/match",
    dataIn: "agence_id, entreprise_id",
    dataOut: "matches row, MATCH_PROPOSED",
    sideEffects: "Calendly links, notification emails",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "dashboard-kpis",
    name: "Dashboard KPIs",
    kind: "component",
    domain: "dashboard_internal",
    role: "recipient",
    actor: "admin",
    route: "app/internal/funnels/[audience]/dashboard",
    dataIn: "agence|entreprise aggregates",
    dataOut: "—",
    sideEffects: "—",
    storage: "supabase",
    status: "wip",
  },
  {
    id: "funnels-api-crud",
    name: "Funnels admin API",
    kind: "api_route",
    domain: "sales_funnel",
    role: "trigger",
    actor: "admin",
    route: "/api/admin/funnels/*",
    dataIn: "funnel.json payload",
    dataOut: "content/funnels files",
    sideEffects: "Publish to preview",
    storage: "hybrid",
    status: "built",
  },
  {
    id: "link-tracking-click",
    name: "Link tracking click",
    kind: "api_route",
    domain: "crm",
    role: "trigger",
    actor: "system",
    route: "/api/link-tracking/click",
    dataIn: "slug, category",
    dataOut: "statut=CLICKED",
    sideEffects: "Redirect to Calendly",
    storage: "supabase",
    status: "built",
  },
  {
    id: "instantly-bypass-cron",
    name: "Instantly bypass cron",
    kind: "cron",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "/api/cron/instantly-bypass-jobs",
    dataIn: "instantly_bypass_jobs (due)",
    dataOut: "pipeline step advance",
    sideEffects: "Instantly API send",
    storage: "supabase",
    status: "built",
  },
];

export const COMPONENTS_REGISTRY = componentsRegistrySchema.parse(RAW_COMPONENTS);

export function getComponentsRegistry(): ComponentEntry[] {
  return COMPONENTS_REGISTRY;
}
