import {
  componentsRegistrySchema,
  type ComponentEntry,
} from "@/lib/admin/architecture/types";

const RAW_COMPONENTS: ComponentEntry[] = [
  {
    id: "fiche-form",
    name: "Fiche form",
    kind: "component",
    domain: "onboarding_funnel",
    role: "trigger",
    actor: "admin",
    route: "components/internal/funnels/fiche-form.tsx",
    dataIn: "—",
    dataOut: "agence|entreprise row, profile.form, statut=ONBOARDED",
    sideEffects: "Génère slug + URLs tracking",
    storage: "supabase",
    status: "built",
  },
  {
    id: "fiche-form-api",
    name: "Onboarding API",
    kind: "api_route",
    domain: "onboarding_funnel",
    role: "trigger",
    actor: "admin",
    route: "/api/admin/onboarding/[category]",
    dataIn: "Payload formulaire JSON",
    dataOut: "INSERT agence|entreprise, profile JSON",
    sideEffects: "Slug + liens réservation",
    storage: "supabase",
    status: "built",
  },
  {
    id: "funnel-editor",
    name: "Éditeur de parcours",
    kind: "component",
    domain: "sales_funnel",
    role: "edition",
    actor: "admin",
    route: "components/internal/funnels/builder/funnel-editor.tsx",
    dataIn: "content/funnels/{audience}/.../funnel.json",
    dataOut: "funnel.json (steps, layout, presets)",
    sideEffects: "Publish via /api/admin/funnels/[slug]/publish",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "mockup-editor",
    name: "Mockup editor",
    kind: "component",
    domain: "marketing",
    role: "edition",
    actor: "admin",
    route: "components/internal/funnels/mockup-editor.tsx",
    dataIn: "agence_demandes row",
    dataOut: "agence_demandes (titre, visibilité, origine)",
    sideEffects: "Carousel homepage agence",
    storage: "supabase",
    status: "built",
  },
  {
    id: "faq-editor",
    name: "FAQ editor",
    kind: "component",
    domain: "sales_funnel",
    role: "edition",
    actor: "admin",
    route: "components/internal/funnels/faq-editor.tsx",
    dataIn: "doc/tech-stack FAQ markdown",
    dataOut: "FAQ content files",
    sideEffects: "Save via /api/admin/faq/[audience]",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "pricing-editor",
    name: "Pricing editor",
    kind: "component",
    domain: "sales_funnel",
    role: "edition",
    actor: "admin",
    route: "components/internal/funnels/pricing-editor.tsx",
    dataIn: "archive/sop/pricing.md",
    dataOut: "Pricing markdown",
    sideEffects: "Save via /api/admin/pricing/[audience]",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "legal-doc",
    name: "Legal doc editor",
    kind: "component",
    domain: "sales_funnel",
    role: "edition",
    actor: "admin",
    route: "components/internal/funnels/legal-doc.tsx",
    dataIn: "doc/tech-stack legal markdown",
    dataOut: "CGV, mentions, confidentialité",
    sideEffects: "—",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "agence-carousel",
    name: "Agence demandes carousel",
    kind: "component",
    domain: "marketing",
    role: "recipient",
    actor: "system",
    route: "components/agence/bande-projets.tsx",
    dataIn: "agence_demandes (visible, dates)",
    dataOut: "—",
    sideEffects: "—",
    storage: "supabase",
    status: "built",
  },
  {
    id: "webhook-calendly",
    name: "Calendly webhook",
    kind: "webhook",
    domain: "crm",
    role: "orchestrator",
    actor: "system",
    route: "/api/webhooks/calendly",
    dataIn: "invitee.created|canceled payload",
    dataOut: "statut, calendly_*, scheduled_at",
    sideEffects: "Enqueue booking_email_jobs, sync Instantly",
    storage: "supabase",
    status: "built",
  },
  {
    id: "webhook-instantly",
    name: "Instantly webhook",
    kind: "webhook",
    domain: "crm",
    role: "orchestrator",
    actor: "system",
    route: "/api/webhooks/instantly",
    dataIn: "Instantly event payload",
    dataOut: "instantly_bypass_events, pipeline step",
    sideEffects: "Bypass subsequence sends",
    storage: "supabase",
    status: "built",
  },
  {
    id: "webhook-instantly-reply",
    name: "Instantly reply webhook",
    kind: "webhook",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "/api/webhooks/instantly/reply",
    dataIn: "Instantly reply event payload",
    dataOut: "ai_reply_agent_jobs, thread state",
    sideEffects: "Enqueue AI reply jobs (streamlit-reply-agent)",
    storage: "supabase",
    status: "built",
  },
  {
    id: "cron-booking-emails",
    name: "Booking emails cron",
    kind: "cron",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "/api/cron/booking-emails",
    dataIn: "booking_email_jobs (due)",
    dataOut: "job status sent|failed",
    sideEffects: "Resend send, engagement tracking",
    storage: "supabase",
    status: "built",
  },
  {
    id: "cron-calendly-seat-check",
    name: "Calendly seat check cron",
    kind: "cron",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "/api/cron/calendly-seat-check",
    dataIn: "calendly_seat_onboarding (active rows)",
    dataOut: "status transitions, reminder sends",
    sideEffects: "Resend reminder, Calendly org API poll",
    storage: "supabase",
    status: "built",
  },
  {
    id: "calendly-seat-orchestrator",
    name: "Calendly seat onboarding orchestrator",
    kind: "orchestrator",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "lib/calendly-seat-onboarding/orchestrator.ts",
    dataIn: "agence lead, Stripe payment webhook",
    dataOut: "calendly_seat_onboarding row, product emails",
    sideEffects: "Welcome email on payment, reminder after 24h",
    storage: "supabase",
    status: "built",
  },
  {
    id: "calendly-org-api",
    name: "Calendly organization API client",
    kind: "api_route",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "lib/calendly/org.ts",
    dataIn: "CALENDLY_API_TOKEN, client email",
    dataOut: "invitation status, membership",
    sideEffects: "Read-only Calendly org poll",
    storage: "none",
    status: "built",
  },
  {
    id: "booking-orchestrator",
    name: "Booking communication orchestrator",
    kind: "orchestrator",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "lib/booking-communication/orchestrator.ts",
    dataIn: "lead row, profile.communication.delays",
    dataOut: "booking_email_jobs inserts",
    sideEffects: "Schedule/cancel emails, send windows Paris",
    storage: "supabase",
    status: "built",
  },
  {
    id: "streamlit-links",
    name: "Streamlit CRM links",
    kind: "component",
    domain: "dashboard_internal",
    role: "trigger",
    actor: "admin",
    route: "app/streamlit_links/app.py",
    dataIn: "agence|entreprise rows",
    dataOut: "statut PATCH via API",
    sideEffects: "Provision links, promote statut",
    storage: "supabase",
    status: "built",
  },
  {
    id: "streamlit-booking-resend",
    name: "Streamlit booking templates",
    kind: "component",
    domain: "dashboard_internal",
    role: "edition",
    actor: "admin",
    route: "app/streamlit_booking_resend/app.py",
    dataIn: "booking_email_templates",
    dataOut: "template HTML/subject",
    sideEffects: "—",
    storage: "supabase",
    status: "built",
  },
  {
    id: "ai-reply-agent-cron",
    name: "AI reply agent cron",
    kind: "cron",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "/api/cron/ai-reply-agent-jobs",
    dataIn: "ai_reply_agent_jobs (due)",
    dataOut: "messages sent, Grok cost",
    sideEffects: "Resend send, Instantly sync",
    storage: "supabase",
    status: "built",
  },
  {
    id: "dashboard-onboarding-form",
    name: "Dashboard onboarding form",
    kind: "component",
    domain: "dashboard_client",
    role: "trigger",
    actor: "client",
    route: "components/dashboard/onboarding-form-modal.tsx",
    dataIn: "DashboardData.form",
    dataOut: "profile.form, completeOnboarding",
    sideEffects: "Calendly seat invitation email",
    storage: "supabase",
    status: "built",
  },
  {
    id: "onboarding-client-form",
    name: "Client onboarding form",
    kind: "component",
    domain: "onboarding_funnel",
    role: "trigger",
    actor: "client",
    route: "app/onboarding/[category]/page.tsx",
    dataIn: "—",
    dataOut: "profile.form, statut=ONBOARDED",
    sideEffects: "—",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "deliverance-timeline",
    name: "Deliverance timeline",
    kind: "component",
    domain: "dashboard_client",
    role: "recipient",
    actor: "client",
    route: "app/suivi/[category]/[slug]/page.tsx",
    dataIn: "profile.display.timeline, deliverance_step",
    dataOut: "—",
    sideEffects: "—",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "post-rdv-survey",
    name: "Post-RDV survey",
    kind: "component",
    domain: "dashboard_client",
    role: "trigger",
    actor: "client",
    route: "app/survey/[token]/page.tsx",
    dataIn: "profile (token validation)",
    dataOut: "profile.survey, statut=SOLD|IN_DELIVERANCE",
    sideEffects: "Enqueue post-survey emails",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "matching-admin-action",
    name: "Mettre en lien (admin)",
    kind: "api_route",
    domain: "dashboard_internal",
    role: "trigger",
    actor: "admin",
    route: "/api/deliverance/match",
    dataIn: "agence_id, entreprise_id",
    dataOut: "matches row, MATCH_PROPOSED",
    sideEffects: "Calendly links, notification emails",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "dashboard-kpis",
    name: "Dashboard state reference",
    kind: "component",
    domain: "dashboard_internal",
    role: "recipient",
    actor: "admin",
    route: "components/internal/funnels/dashboard/dashboard-state-table.tsx",
    dataIn: "dashboard modes documentation",
    dataOut: "—",
    sideEffects: "—",
    storage: "none",
    status: "spec",
  },
  {
    id: "funnels-api-crud",
    name: "API admin parcours",
    kind: "api_route",
    domain: "sales_funnel",
    role: "trigger",
    actor: "admin",
    route: "/api/admin/funnels/*",
    dataIn: "funnel.json payload",
    dataOut: "content/funnels files",
    sideEffects: "Publish to preview",
    storage: "hybrid",
    status: "built",
  },
  {
    id: "link-tracking-click",
    name: "Link tracking click",
    kind: "api_route",
    domain: "crm",
    role: "trigger",
    actor: "system",
    route: "/api/link-tracking/click",
    dataIn: "slug, category",
    dataOut: "statut=CLICKED",
    sideEffects: "Redirect to Calendly",
    storage: "supabase",
    status: "built",
  },
  {
    id: "instantly-bypass-cron",
    name: "Instantly bypass cron",
    kind: "cron",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "/api/cron/instantly-bypass-jobs",
    dataIn: "instantly_bypass_jobs (due)",
    dataOut: "pipeline step advance",
    sideEffects: "Instantly API send",
    storage: "supabase",
    status: "built",
  },
  {
    id: "webhook-resend",
    name: "Resend webhook",
    kind: "webhook",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "/api/webhooks/resend",
    dataIn: "Resend event payload",
    dataOut: "email delivery status",
    sideEffects: "Engagement tracking",
    storage: "supabase",
    status: "built",
  },
  {
    id: "pipeline-cron",
    name: "Instantly bypass pipeline cron",
    kind: "cron",
    domain: "communication",
    role: "orchestrator",
    actor: "system",
    route: "/api/cron/instantly-bypass-pipeline",
    dataIn: "instantly_bypass pipeline queue",
    dataOut: "pipeline step advance",
    sideEffects: "Instantly API orchestration",
    storage: "supabase",
    status: "built",
  },
  {
    id: "admin-demandes-api",
    name: "Mockup demandes API",
    kind: "api_route",
    domain: "marketing",
    role: "trigger",
    actor: "admin",
    route: "/api/admin/demandes",
    dataIn: "agence_demandes patch payload",
    dataOut: "agence_demandes row",
    sideEffects: "Carousel + MockupDatas refresh",
    storage: "supabase",
    status: "built",
  },
  {
    id: "calendly-availability-api",
    name: "Calendly availability API",
    kind: "api_route",
    domain: "sales_funnel",
    role: "recipient",
    actor: "system",
    route: "/api/calendly/availability",
    dataIn: "Calendly scheduling links",
    dataOut: "available slots JSON",
    sideEffects: "—",
    storage: "none",
    status: "built",
  },
  {
    id: "streamlit-subsequence",
    name: "Streamlit subsequences",
    kind: "component",
    domain: "communication",
    role: "edition",
    actor: "admin",
    route: "app/streamlit_subsequence/app.py",
    dataIn: "Instantly campaigns, subsequence config",
    dataOut: "subsequence steps, bypass jobs",
    sideEffects: "Instantly API, pipeline bootstrap",
    storage: "supabase",
    status: "built",
  },
  {
    id: "streamlit-reply-agent",
    name: "Streamlit reply agent",
    kind: "component",
    domain: "communication",
    role: "edition",
    actor: "admin",
    route: "app/streamlit_reply_agent/app.py",
    dataIn: "Instantly leads, prompt store",
    dataOut: "AI reply jobs, prompt files",
    sideEffects: "Resend send, Grok cost",
    storage: "supabase",
    status: "built",
  },
  {
    id: "streamlit-stats",
    name: "Streamlit outreach stats",
    kind: "component",
    domain: "sales_funnel",
    role: "edition",
    actor: "admin",
    route: "app/streamlit_stats/app.py",
    dataIn: "Instantly campaign metrics (manual/API)",
    dataOut: "campaign_stats.json",
    sideEffects: "—",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "streamlit-demands",
    name: "Streamlit mockup demandes",
    kind: "component",
    domain: "marketing",
    role: "edition",
    actor: "admin",
    route: "app/streamlit_demands/app.py",
    dataIn: "agence_demandes rows",
    dataOut: "agence_demandes (demande, teaser)",
    sideEffects: "Carousel homepage refresh",
    storage: "supabase",
    status: "built",
  },
  {
    id: "streamlit-scraper",
    name: "Streamlit Outscraper pipeline",
    kind: "component",
    domain: "crm",
    role: "trigger",
    actor: "admin",
    route: "app/streamlit_scraper/app.py",
    dataIn: "Outscraper presets, niche configs",
    dataOut: "outscraper_leads.csv, enrich_audit.csv",
    sideEffects: "Instantly campaign push, scrape_state.json",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "streamlit-clean",
    name: "Streamlit email cleaner",
    kind: "component",
    domain: "crm",
    role: "trigger",
    actor: "admin",
    route: "app/streamlit_clean/app.py",
    dataIn: "CSV leads, Instantly lists/campaigns",
    dataOut: "Verified leads, cleaned CSV",
    sideEffects: "MyEmailVerifier API, Instantly upload",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "mkt-home",
    name: "Homepage comptable",
    kind: "component",
    domain: "marketing",
    role: "recipient",
    actor: "client",
    route: "app/page.tsx",
    dataIn: "comptable_demandes carousel, copy",
    dataOut: "—",
    sideEffects: "—",
    storage: "supabase",
    status: "built",
  },
  {
    id: "mkt-agence",
    name: "Landing agence",
    kind: "component",
    domain: "marketing",
    role: "recipient",
    actor: "client",
    route: "app/agence/page.tsx",
    dataIn: "agence_demandes carousel, copy",
    dataOut: "—",
    sideEffects: "—",
    storage: "supabase",
    status: "built",
  },
  {
    id: "mkt-entreprise",
    name: "Landing comptable (legacy id)",
    kind: "component",
    domain: "marketing",
    role: "recipient",
    actor: "client",
    route: "app/page.tsx",
    dataIn: "comptable_demandes carousel, copy",
    dataOut: "—",
    sideEffects: "—",
    storage: "supabase",
    status: "built",
  },
  {
    id: "mkt-faq",
    name: "FAQ marketing",
    kind: "component",
    domain: "marketing",
    role: "recipient",
    actor: "client",
    route: "app/faq/page.tsx",
    dataIn: "FAQ markdown",
    dataOut: "—",
    sideEffects: "—",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "mkt-cvg",
    name: "CGV marketing",
    kind: "component",
    domain: "marketing",
    role: "recipient",
    actor: "client",
    route: "app/cvg/page.tsx|app/cvg/[doc]/page.tsx",
    dataIn: "CGV markdown",
    dataOut: "—",
    sideEffects: "—",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "mkt-legal",
    name: "Pages légales",
    kind: "component",
    domain: "marketing",
    role: "recipient",
    actor: "client",
    route: "app/a-propos|mentions-legales|confidentialite",
    dataIn: "Legal markdown",
    dataOut: "—",
    sideEffects: "—",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "sales-res-html",
    name: "Reservation Calendly HTML",
    kind: "component",
    domain: "sales_funnel",
    role: "trigger",
    actor: "client",
    route: "public/reservation*.html",
    dataIn: "—",
    dataOut: "Calendly booking (vente)",
    sideEffects: "webhook-calendly",
    storage: "none",
    status: "built",
  },
  {
    id: "int-home",
    name: "Internal hub",
    kind: "component",
    domain: "dashboard_internal",
    role: "recipient",
    actor: "admin",
    route: "app/internal/(shell)/page.tsx",
    dataIn: "—",
    dataOut: "—",
    sideEffects: "—",
    storage: "none",
    status: "built",
  },
  {
    id: "int-funnels",
    name: "Hub parcours internal",
    kind: "component",
    domain: "sales_funnel",
    role: "edition",
    actor: "admin",
    route: "app/internal/funnels/page.tsx",
    dataIn: "content/funnels catalog",
    dataOut: "—",
    sideEffects: "—",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "int-components",
    name: "Components inventory",
    kind: "component",
    domain: "dashboard_internal",
    role: "recipient",
    actor: "admin",
    route: "app/internal/(shell)/components/page.tsx",
    dataIn: "components-registry.ts",
    dataOut: "—",
    sideEffects: "—",
    storage: "none",
    status: "built",
  },
  {
    id: "int-database",
    name: "Database inventory",
    kind: "component",
    domain: "dashboard_internal",
    role: "recipient",
    actor: "admin",
    route: "app/internal/(shell)/database/page.tsx",
    dataIn: "database-registry.ts",
    dataOut: "—",
    sideEffects: "—",
    storage: "none",
    status: "built",
  },
  {
    id: "clients-table",
    name: "Clients table",
    kind: "component",
    domain: "dashboard_internal",
    role: "recipient",
    actor: "admin",
    route: "/internal/funnels/agence/clients",
    dataIn: "agence|entreprise rows, matches, statuts",
    dataOut: "—",
    sideEffects: "Propose agence, cockpit ops, délivrance",
    storage: "supabase",
    status: "built",
  },
  {
    id: "rdv-association-ui",
    name: "RDV association UI",
    kind: "component",
    domain: "dashboard_internal",
    role: "trigger",
    actor: "admin",
    route: "—",
    dataIn: "Calendly link, entreprise list",
    dataOut: "match entreprise ↔ rendez-vous",
    sideEffects: "DB update, Resend, tracking",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "upsell-admin-action",
    name: "Proposer upsell",
    kind: "api_route",
    domain: "dashboard_internal",
    role: "trigger",
    actor: "admin",
    route: "—",
    dataIn: "agence_id, trigger MEETING_10|COMPLETED|manual",
    dataOut: "upsell sequence enqueue",
    sideEffects: "Resend upsell sequence",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "agenda",
    name: "Agenda (session)",
    kind: "component",
    domain: "sales_funnel",
    role: "recipient",
    actor: "admin",
    route: "—",
    dataIn: "global_settings.waiting_queue_days, Calendly slots",
    dataOut: "—",
    sideEffects: "—",
    storage: "hybrid",
    status: "spec",
  },
  {
    id: "global-settings",
    name: "Global settings",
    kind: "component",
    domain: "sales_funnel",
    role: "edition",
    actor: "admin",
    route: "/internal/funnels/{audience}/sales/funnel/settings",
    dataIn: "—",
    dataOut: "global config (file d'attente 15 jours)",
    sideEffects: "Agenda blocked period",
    storage: "hybrid",
    status: "built",
  },
  {
    id: "mockup-datas",
    name: "Mockup datas (session)",
    kind: "component",
    domain: "sales_funnel",
    role: "recipient",
    actor: "admin",
    route: "—",
    dataIn: "agence_demandes (35 demandes)",
    dataOut: "—",
    sideEffects: "—",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "sales-metrics",
    name: "Métriques session",
    kind: "component",
    domain: "sales_funnel",
    role: "recipient",
    actor: "admin",
    route: "—",
    dataIn: "Calendly webhooks, local call notes JSON",
    dataOut: "PAID|NO SHOW|NOT PAID annotations",
    sideEffects: "—",
    storage: "hybrid",
    status: "spec",
  },
  {
    id: "previsionnel",
    name: "Previsionnel tables",
    kind: "component",
    domain: "sales_funnel",
    role: "recipient",
    actor: "admin",
    route: "—",
    dataIn: "Meetings planifiés, config closing rate",
    dataOut: "Pipeline prévu, revenue réel, performance",
    sideEffects: "—",
    storage: "hybrid",
    status: "spec",
  },
  {
    id: "sequence-editor",
    name: "Sequence editor (SequenceDropdown)",
    kind: "component",
    domain: "communication",
    role: "edition",
    actor: "admin",
    route: "components/internal/funnels/sequence-editor/sequence-dropdown.tsx",
    dataIn: "booking_email_templates, instantly_bypass_templates, ai_reply_agent_config",
    dataOut: "steps, delays, variables, preview",
    sideEffects: "Save to SoT",
    storage: "hybrid",
    status: "built",
  },
  {
    id: "email-sequences-table",
    name: "Email sequences dashboard",
    kind: "component",
    domain: "communication",
    role: "edition",
    actor: "admin",
    route: "/internal/funnels/[audience]/emails",
    dataIn: "lib/admin/email-sequences/registry.ts (incl. calendly-seat-onboarding)",
    dataOut: "sequence list, navigation to editors",
    sideEffects: "—",
    storage: "filesystem",
    status: "built",
  },
  {
    id: "meeting-sequence-ui",
    name: "Meeting sequence UI",
    kind: "component",
    domain: "communication",
    role: "edition",
    actor: "admin",
    route: "/internal/funnels/[audience]/emails/meeting-agence",
    dataIn: "booking_email_templates, leads",
    dataOut: "SEQUENCES editor (MEETINGS tab still Streamlit)",
    sideEffects: "Partial replace streamlit_booking_resend",
    storage: "supabase",
    status: "built",
  },
  {
    id: "calendly-seat-sequence-ui",
    name: "Calendly seat onboarding sequence UI",
    kind: "component",
    domain: "communication",
    role: "edition",
    actor: "admin",
    route: "/internal/funnels/agence/emails/calendly-seat-onboarding",
    dataIn: "booking_email_templates (product_calendly_*), calendly_seat_onboarding",
    dataOut: "Editable welcome + reminder templates",
    sideEffects: "Save to booking_email_templates",
    storage: "supabase",
    status: "built",
  },
  {
    id: "no-show-action",
    name: "Mark as no-show",
    kind: "api_route",
    domain: "communication",
    role: "trigger",
    actor: "admin",
    route: "—",
    dataIn: "lead_id, meeting_id",
    dataOut: "statut=NO SHOW, no-show sequence",
    sideEffects: "Resend 3-email sequence",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "preclose-sequence-trigger",
    name: "Pre-close sequence trigger",
    kind: "api_route",
    domain: "sales_funnel",
    role: "trigger",
    actor: "admin",
    route: "—",
    dataIn: "lead_id (indécis post-call)",
    dataOut: "pre-close email sequence",
    sideEffects: "Resend 3-email sequence",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "int-leads",
    name: "Internal leads list",
    kind: "component",
    domain: "dashboard_internal",
    role: "recipient",
    actor: "admin",
    route: "—",
    dataIn: "agence|entreprise CRM rows",
    dataOut: "—",
    sideEffects: "—",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "int-lead-detail",
    name: "Internal lead detail",
    kind: "component",
    domain: "dashboard_internal",
    role: "recipient",
    actor: "admin",
    route: "—",
    dataIn: "lead profile, statut, history",
    dataOut: "—",
    sideEffects: "—",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "int-pay-link",
    name: "Stripe payment link",
    kind: "component",
    domain: "sales_funnel",
    role: "trigger",
    actor: "admin",
    route: "—",
    dataIn: "lead_id, offer",
    dataOut: "Stripe checkout URL",
    sideEffects: "Payment webhook → PAID",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "int-appointments",
    name: "Internal appointments",
    kind: "component",
    domain: "dashboard_internal",
    role: "trigger",
    actor: "admin",
    route: "—",
    dataIn: "Calendly bookings",
    dataOut: "—",
    sideEffects: "—",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "int-templates",
    name: "Booking email templates",
    kind: "component",
    domain: "communication",
    role: "edition",
    actor: "admin",
    route: "—",
    dataIn: "booking_email_templates",
    dataOut: "template HTML/subject",
    sideEffects: "—",
    storage: "supabase",
    status: "spec",
  },
  {
    id: "int-sales",
    name: "Édition session",
    kind: "component",
    domain: "sales_funnel",
    role: "edition",
    actor: "admin",
    route: "—",
    dataIn: "Sales config, sequences",
    dataOut: "—",
    sideEffects: "—",
    storage: "hybrid",
    status: "spec",
  },
  {
    id: "webhook-supabase-link-tracking",
    name: "Supabase link tracking webhook",
    kind: "webhook",
    domain: "crm",
    role: "orchestrator",
    actor: "system",
    route: "/api/webhooks/supabase-link-tracking",
    dataIn: "Supabase DB change payload",
    dataOut: "link tracking row sync",
    sideEffects: "Statut sync with CRM",
    storage: "supabase",
    status: "built",
  },
  {
    id: "link-tracking-api",
    name: "Link tracking API",
    kind: "api_route",
    domain: "crm",
    role: "trigger",
    actor: "system",
    route: "/api/link-tracking/*",
    dataIn: "slug, category, confirm payload",
    dataOut: "statut, Calendly links JSON",
    sideEffects: "Redirect, sync-status",
    storage: "supabase",
    status: "built",
  },
  {
    id: "booking-communication-api",
    name: "Booking communication API",
    kind: "api_route",
    domain: "communication",
    role: "trigger",
    actor: "admin",
    route: "/api/booking-communication/*",
    dataIn: "templates, trigger payload, lead row",
    dataOut: "booking_email_jobs, rendered HTML",
    sideEffects: "Resend send, orchestrator enqueue",
    storage: "supabase",
    status: "built",
  },
  {
    id: "modalites-campaign-page",
    name: "Campagne modalités Hercule",
    kind: "component",
    domain: "dashboard_internal",
    role: "trigger",
    actor: "admin",
    route: "/internal/modalites",
    dataIn: "Calendly upcoming bookings, agence|entreprise leads",
    dataOut: "booking_email_jobs modalites_ask/cancel, unique confirm URLs",
    sideEffects: "Resend send, Calendly cancel after 24h if unconfirmed",
    storage: "supabase",
    status: "wip",
  },
];

export const COMPONENTS_REGISTRY = componentsRegistrySchema.parse(RAW_COMPONENTS);

export function getComponentsRegistry(): ComponentEntry[] {
  return COMPONENTS_REGISTRY;
}
