import {
  databaseRegistrySchema,
  type DatabaseEntry,
} from "@/lib/admin/architecture/types";

const RAW_DATABASE: DatabaseEntry[] = [
  {
    id: "agence",
    label: "Agence leads",
    domain: "product",
    purpose: "Fiche agence web — statut produit, profile, match, Calendly",
    keyColumns: "id, email, statut, slug, profile, matched_entreprise_id",
    writers: ["admin", "client", "webhook"],
    readers: ["admin", "client", "cron"],
    profileKeys: "form, communication.delays, display.timeline, match",
    relatedTables: ["booking_email_jobs", "matches"],
    status: "migrated",
  },
  {
    id: "entreprise",
    label: "Entreprise leads",
    domain: "product",
    purpose: "Fiche entreprise cliente — miroir agence",
    keyColumns: "id, email, statut, slug, profile, matched_agence_id",
    writers: ["admin", "client", "webhook"],
    readers: ["admin", "client", "cron"],
    profileKeys: "form, communication.delays, display.timeline, match",
    relatedTables: ["booking_email_jobs", "matches"],
    status: "migrated",
  },
  {
    id: "matches",
    label: "Matches",
    domain: "product",
    purpose: "Historique liaison agence ↔ entreprise",
    keyColumns: "id, agence_id, entreprise_id, matched_at, created_by",
    writers: ["admin"],
    readers: ["admin"],
    profileKeys: "—",
    relatedTables: ["agence", "entreprise"],
    status: "planned",
  },
  {
    id: "booking_email_jobs",
    label: "Booking email jobs",
    domain: "communication",
    purpose: "Queue d'envoi emails booking — quand envoyer",
    keyColumns: "id, lead_category, lead_id, email_type, scheduled_for, status",
    writers: ["admin", "webhook", "cron"],
    readers: ["cron", "admin"],
    profileKeys: "communication.delays (source dates)",
    relatedTables: ["agence", "entreprise", "booking_email_templates"],
    status: "migrated",
  },
  {
    id: "booking_email_templates",
    label: "Booking email templates",
    domain: "communication",
    purpose: "Corps et sujet des emails booking",
    keyColumns: "id, category, email_type, subject, html_body",
    writers: ["admin"],
    readers: ["cron", "admin"],
    profileKeys: "form.* (variables render)",
    relatedTables: ["booking_email_jobs"],
    status: "migrated",
  },
  {
    id: "agence_demandes",
    label: "Agence demandes",
    domain: "marketing",
    purpose: "Cartes carousel homepage agence (demande/teaser)",
    keyColumns: "id, type, titre, visible, date_debut, date_fin, origine",
    writers: ["admin"],
    readers: ["public", "admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "instantly_bypass_templates",
    label: "Instantly bypass templates",
    domain: "instantly",
    purpose: "Copy E1/E2/E3 interested + no-show",
    keyColumns: "id, step, subject, body",
    writers: ["admin"],
    readers: ["cron", "admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_jobs"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_config",
    label: "Instantly bypass config",
    domain: "instantly",
    purpose: "Subsequence IDs par campagne",
    keyColumns: "campaign_id, subsequence_ids",
    writers: ["admin"],
    readers: ["cron", "webhook", "admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_pipeline"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_events",
    label: "Instantly bypass events",
    domain: "instantly",
    purpose: "Idempotence et audit webhook",
    keyColumns: "id, event_id, campaign_id, email, step",
    writers: ["webhook"],
    readers: ["admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_pipeline"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_jobs",
    label: "Instantly bypass jobs",
    domain: "instantly",
    purpose: "Envois programmés hors heures ouvrées",
    keyColumns: "id, pipeline_id, scheduled_for, status",
    writers: ["webhook", "cron"],
    readers: ["cron", "admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_pipeline"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_pipeline",
    label: "Instantly bypass pipeline",
    domain: "instantly",
    purpose: "Étape courante par lead (step_0…step_3)",
    keyColumns: "id, campaign_id, email, current_step",
    writers: ["webhook", "cron"],
    readers: ["cron", "admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_jobs"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_settings",
    label: "Instantly bypass settings",
    domain: "instantly",
    purpose: "Toggles webhook bypass",
    keyColumns: "key, value",
    writers: ["admin"],
    readers: ["webhook", "admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_config",
    label: "AI reply agent config",
    domain: "ai",
    purpose: "Mapping campagne → prompt niche",
    keyColumns: "campaign_id, niche, system_prompt",
    writers: ["admin"],
    readers: ["cron", "webhook", "admin"],
    profileKeys: "—",
    relatedTables: ["ai_reply_agent_messages"],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_messages",
    label: "AI reply agent messages",
    domain: "ai",
    purpose: "Inbound/outbound + statut AI",
    keyColumns: "id, thread_id, direction, ai_status, body",
    writers: ["webhook", "cron"],
    readers: ["admin", "cron"],
    profileKeys: "—",
    relatedTables: ["ai_reply_agent_jobs", "ai_reply_agent_leads"],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_jobs",
    label: "AI reply agent jobs",
    domain: "ai",
    purpose: "Envois différés manuels/auto",
    keyColumns: "id, message_id, scheduled_for, status",
    writers: ["webhook", "cron"],
    readers: ["cron", "admin"],
    profileKeys: "—",
    relatedTables: ["ai_reply_agent_messages"],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_leads",
    label: "AI reply agent leads",
    domain: "ai",
    purpose: "Métadonnées lead pour inbox AI",
    keyColumns: "id, email, campaign_id, niche",
    writers: ["webhook"],
    readers: ["admin", "cron"],
    profileKeys: "—",
    relatedTables: ["ai_reply_agent_messages"],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_blocklist",
    label: "AI reply agent blocklist",
    domain: "ai",
    purpose: "Suppression emails de l'agent",
    keyColumns: "email, reason",
    writers: ["admin"],
    readers: ["webhook", "admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_settings",
    label: "AI reply agent settings",
    domain: "ai",
    purpose: "Toggle webhook global agent",
    keyColumns: "key, value",
    writers: ["admin"],
    readers: ["webhook", "admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
];

export const DATABASE_REGISTRY = databaseRegistrySchema.parse(RAW_DATABASE);

export function getDatabaseRegistry(): DatabaseEntry[] {
  return DATABASE_REGISTRY;
}
