import {
  databaseRegistrySchema,
  type DatabaseEntry,
} from "@/lib/admin/architecture/types";

const RAW_DATABASE: DatabaseEntry[] = [
  {
    id: "agence",
    label: "Agence leads",
    domain: "product",
    purpose: "Fiche agence web — statut produit, profile, match, Calendly",
    keyColumns: "id, email, statut, product_statut, slug, profile, retraction_status, retraction_ends_at, retraction_waived_at, offer_type, credits_remaining, active_match_id, deliverance_started_at",
    writers: ["admin", "client", "webhook"],
    readers: ["admin", "client", "cron"],
    profileKeys: "form, communication.delays, display.timeline, match",
    relatedTables: ["booking_email_jobs", "matches", "appointments", "payments"],
    status: "migrated",
  },
  {
    id: "entreprise",
    label: "Entreprise leads",
    domain: "product",
    purpose: "Fiche TPE web (matière matching) — miroir agence sans niche comptable",
    keyColumns: "id, email, statut, slug, profile, matched_agence_id",
    writers: ["admin", "client", "webhook"],
    readers: ["admin", "client", "cron"],
    profileKeys: "form, communication.delays, display.timeline, match",
    relatedTables: ["booking_email_jobs", "matches"],
    status: "migrated",
  },
  {
    id: "comptable",
    label: "Comptable leads",
    domain: "product",
    purpose: "Fiche cabinet comptable buyer — acquisition, onboarding, Calendly",
    keyColumns: "id, email, statut, product_statut, slug, profile, retraction_status, retraction_ends_at, retraction_waived_at, reservation_comptable_link, confirmation_comptable_link, dashboard_link",
    writers: ["admin", "webhook", "cron"],
    readers: ["admin", "client", "cron"],
    profileKeys: "form, communication.delays, display.timeline",
    relatedTables: ["booking_email_jobs", "payments", "sales_calls"],
    status: "migrated",
  },
  {
    id: "matches",
    label: "Matches",
    domain: "product",
    purpose: "Liaison agence ↔ entreprise — statut proposed|booked|sold, survey tokens, calendly URL",
    keyColumns: "id, agence_id, entreprise_id, status, calendly_url, booking_at, agence_survey_token, entreprise_survey_token, sale_made",
    writers: ["admin", "webhook"],
    readers: ["admin", "cron"],
    profileKeys: "—",
    relatedTables: ["agence", "entreprise", "appointments"],
    status: "migrated",
  },
  {
    id: "appointments",
    label: "Appointments",
    domain: "product",
    purpose: "RDV livraison — SoT attribution counter, survey tokens, statuts no-show/complete",
    keyColumns: "id, match_id, agence_id, entreprise_id, calendly_invitee_uri, status, survey_token_agence, survey_token_entreprise",
    writers: ["admin", "webhook"],
    readers: ["admin", "client"],
    profileKeys: "—",
    relatedTables: ["matches", "agence", "entreprise"],
    status: "migrated",
  },
  {
    id: "payments",
    label: "Payments",
    domain: "product",
    purpose: "Paiements Stripe — agence (starter_998_5/growth_1498_10 + legacy starter_1489_5/monthly_1489/pack_989x3, payment_phase deposit|balance) et comptable (starter_999_5/monthly_1499 abonnements + pack_3x1499 one-shot). Gate délivrance, idempotence stripe_event_id.",
    keyColumns: "id, agence_id, entreprise_id, comptable_id, offer_type, payment_phase, parent_payment_id, amount_cents, status, stripe_checkout_session_id, stripe_subscription_id, stripe_event_id, succeeded_at",
    writers: ["webhook", "admin"],
    readers: ["admin", "client"],
    profileKeys: "—",
    relatedTables: ["agence", "entreprise", "comptable"],
    status: "migrated",
  },
  {
    id: "sales_calls",
    label: "Sales calls",
    domain: "product",
    purpose: "Appels commerciaux Calendly — qualification et statut not_paid/paid",
    keyColumns: "id, agence_id, entreprise_id, comptable_id, email, calendly_invitee_uri, status, forecast_cents, notes",
    writers: ["webhook", "admin"],
    readers: ["admin"],
    profileKeys: "—",
    relatedTables: ["agence", "entreprise", "comptable"],
    status: "migrated",
  },
  {
    id: "booking_email_jobs",
    label: "Booking email jobs",
    domain: "communication",
    purpose: "Queue d'envoi emails booking — quand envoyer",
    keyColumns: "id, lead_category, lead_id, email_type, scheduled_for, status",
    writers: ["admin", "webhook", "cron"],
    readers: ["cron", "admin"],
    profileKeys: "communication.delays (source dates)",
    relatedTables: ["agence", "comptable", "entreprise", "booking_email_templates"],
    status: "migrated",
  },
  {
    id: "booking_email_templates",
    label: "Booking email templates",
    domain: "communication",
    purpose: "Corps et sujet des emails booking",
    keyColumns: "id, category, email_type, subject, html_body",
    writers: ["admin"],
    readers: ["cron", "admin"],
    profileKeys: "form.* (variables render)",
    relatedTables: ["booking_email_jobs"],
    status: "migrated",
  },
  {
    id: "niche_outreach_config",
    label: "Niche outreach config",
    domain: "marketing",
    purpose: "Campagne Instantly + event type Calendly par niche (Bookings CRM)",
    keyColumns: "niche, instantly_campaign_id, calendly_event_type_uri, updated_at, updated_by",
    writers: ["admin"],
    readers: ["admin", "cron"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "email_variable_bindings",
    label: "Email variable bindings",
    domain: "marketing",
    purpose: "Variables template activées par niche pour éditeurs de séquences",
    keyColumns: "niche, variable_key, enabled, base_url_preview",
    writers: ["admin"],
    readers: ["admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "agence_demandes",
    label: "Agence demandes",
    domain: "marketing",
    purpose: "Cartes carousel homepage agence (demande/teaser)",
    keyColumns: "id, type, titre, visible, date_debut, date_fin, origine",
    writers: ["admin"],
    readers: ["public", "admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "funnel_pages",
    label: "Funnel pages",
    domain: "marketing",
    purpose: "Pages funnel — builder /internal/funnels, servies en production",
    keyColumns: "slug, audience, status, tree, published_at",
    writers: ["admin"],
    readers: ["public", "admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "instantly_bypass_templates",
    label: "Instantly bypass templates",
    domain: "instantly",
    purpose: "Copy E1/E2/E3 interested + no-show",
    keyColumns: "id, step, subject, body",
    writers: ["admin"],
    readers: ["cron", "admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_jobs"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_config",
    label: "Instantly bypass config",
    domain: "instantly",
    purpose: "Subsequence IDs par campagne",
    keyColumns: "campaign_id, subsequence_ids",
    writers: ["admin"],
    readers: ["cron", "webhook", "admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_pipeline"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_events",
    label: "Instantly bypass events",
    domain: "instantly",
    purpose: "Idempotence et audit webhook",
    keyColumns: "id, event_id, campaign_id, email, step",
    writers: ["webhook"],
    readers: ["admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_pipeline"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_jobs",
    label: "Instantly bypass jobs",
    domain: "instantly",
    purpose: "Envois programmés hors heures ouvrées",
    keyColumns: "id, pipeline_id, scheduled_for, status",
    writers: ["webhook", "cron"],
    readers: ["cron", "admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_pipeline"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_pipeline",
    label: "Instantly bypass pipeline",
    domain: "instantly",
    purpose: "Étape courante par lead (step_0…step_3)",
    keyColumns: "id, campaign_id, email, current_step",
    writers: ["webhook", "cron"],
    readers: ["cron", "admin"],
    profileKeys: "—",
    relatedTables: ["instantly_bypass_jobs"],
    status: "migrated",
  },
  {
    id: "instantly_bypass_settings",
    label: "Instantly bypass settings",
    domain: "instantly",
    purpose: "Toggles webhook bypass",
    keyColumns: "key, value",
    writers: ["admin"],
    readers: ["webhook", "admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "deliverability_settings",
    label: "Deliverability settings",
    domain: "instantly",
    purpose: "Seuils alerte, cache refresh, emails exclus (panneau ops)",
    keyColumns: "health_score_warn_below, inbox_rate_warn_below, refresh_minutes, excluded_emails",
    writers: ["admin"],
    readers: ["admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_config",
    label: "AI reply agent config",
    domain: "ai",
    purpose: "Mapping campagne → prompt niche",
    keyColumns: "campaign_id, niche, system_prompt",
    writers: ["admin"],
    readers: ["cron", "webhook", "admin"],
    profileKeys: "—",
    relatedTables: ["ai_reply_agent_messages"],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_messages",
    label: "AI reply agent messages",
    domain: "ai",
    purpose: "Inbound/outbound + statut AI",
    keyColumns: "id, thread_id, direction, ai_status, body",
    writers: ["webhook", "cron"],
    readers: ["admin", "cron"],
    profileKeys: "—",
    relatedTables: ["ai_reply_agent_jobs", "ai_reply_agent_leads"],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_jobs",
    label: "AI reply agent jobs",
    domain: "ai",
    purpose: "Envois différés manuels/auto",
    keyColumns: "id, message_id, scheduled_for, status",
    writers: ["webhook", "cron"],
    readers: ["cron", "admin"],
    profileKeys: "—",
    relatedTables: ["ai_reply_agent_messages"],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_leads",
    label: "AI reply agent leads",
    domain: "ai",
    purpose: "Métadonnées lead pour inbox AI",
    keyColumns: "id, email, campaign_id, niche",
    writers: ["webhook"],
    readers: ["admin", "cron"],
    profileKeys: "—",
    relatedTables: ["ai_reply_agent_messages"],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_blocklist",
    label: "AI reply agent blocklist",
    domain: "ai",
    purpose: "Suppression emails de l'agent",
    keyColumns: "email, reason",
    writers: ["admin"],
    readers: ["webhook", "admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
  {
    id: "ai_reply_agent_settings",
    label: "AI reply agent settings",
    domain: "ai",
    purpose: "Toggle webhook global agent",
    keyColumns: "key, value",
    writers: ["admin"],
    readers: ["webhook", "admin"],
    profileKeys: "—",
    relatedTables: [],
    status: "migrated",
  },
];

export const DATABASE_REGISTRY = databaseRegistrySchema.parse(RAW_DATABASE);

export function getDatabaseRegistry(): DatabaseEntry[] {
  return DATABASE_REGISTRY;
}
