"""Comptables (France) scraper preset — static rules; secrets come from config_loader."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "comptables"
PRESET_LABEL = "Comptables (France)"

_LIST_ID = "a3cd8ff6-34e6-4864-9ed7-c066a8ca20c9"
_CAMPAIGN_ID = "affdc6cf-1e4d-496b-a0b2-cf3a02f073aa"

COMPTABLES_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [_LIST_ID],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [_CAMPAIGN_ID],
    "INSTANTLY_PUSH_EVERY": 100,
    "ENRICH_ENABLED": True,
    "ENRICH_BATCH_SIZE": 50,
    "ENRICH_CONCURRENCY": 20,
    "ENRICH_TIMEOUT_MS": 10000,
    "ENRICH_INCLUDED_KEYWORDS": [
        "expert-comptable",
        "expertise comptable",
        "comptabilité",
        "tenue de comptabilité",
        "déclaration fiscale",
        "liasse fiscale",
        "audit",
        "commissaire aux comptes",
        "social et fiscal",
        "paie",
        "bulletins de paie",
        "bilan",
        "conseil fiscal",
        "cabinet comptable",
        "ECG",
        "Cerfrance",
    ],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [
        "agence immobilière",
        "notaire",
        "avocat",
        "gestion de patrimoine",
        "CGP",
        "IFA",
        "wealth management",
        "agence de communication",
        "growth hacking",
        "google ads",
        "seo",
        "assurance auto",
        "recrutement",
        "centre de formation",
    ],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [
        "logiciel comptable",
        "ERP",
        "Sage",
        "Cegid",
        "formation comptable",
        "stage comptabilité",
        "banque",
        "crédit consommation",
    ],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 6,
    "OUTSCRAPER_LIMIT_PER_QUERY": 30,
    "OUTSCRAPER_POLL_INITIAL_S": 45,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 600,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 8,
    "TARGET_LEADS": 5_000,
    "TARGET_MODE": "instantly_pushed",
    "SERVICE_DEFAULT": "Expertise Comptable",
    "SERVICE_RULES": [
        {"label": "Audit", "keywords": ["audit", "commissaire aux comptes", "commissariat aux comptes"]},
        {"label": "Paie & Social", "keywords": ["paie", "bulletins de paie", "social et fiscal", "paie et social", "gestion paie"]},
        {"label": "Conseil Fiscal", "keywords": ["conseil fiscal", "déclaration fiscale", "liasse fiscale", "conseil juridique fiscal"]},
        {"label": "Tenue de Comptabilité", "keywords": ["tenue de comptabilité", "comptabilité", "externalisation comptable", "bilan"]},
    ],
    "KEYWORDS": [
        "expert-comptable",
        "cabinet expert-comptable",
        "cabinet comptable",
        "expertise comptable",
        "commissaire aux comptes",
        "fiduciaire",
        "cabinet d'expertise comptable",
        "expert comptable indépendant",
        "ECG",
        "comptabilité entreprise",
        "tenue de comptabilité",
        "audit comptable",
        "Cerfrance",
        "cabinet comptable PME",
    ],
    "EXPANSION_KEYWORDS": [
        "expert-comptable TPE",
        "social et fiscal",
        "déclaration fiscale",
        "liasse fiscale",
        "bilan comptable",
        "paie et social",
        "conseil juridique fiscal",
        "réseau comptable",
        "commissariat aux comptes",
        "externalisation comptable",
        "gestion paie",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": True,
    "PAPPERS_MIN_EMPLOYEES": 10,
    "PAPPERS_ON_UNKNOWN": "reject",
    "PAPPERS_CONCURRENCY": 20,
    "PAPPERS_NAF_PREFIXES": [
        "69.20",
    ],
    "NICHE_METADATA": {
        "angle": "Cabinets d'expertise comptable et fiduciaires.",
        "valeur_client": "",
        "effectif_cible": "10+ salariés",
    },
}

CONFIG = COMPTABLES_CONFIG
