"""Conseillers financiers (CGP) scraper preset — static rules; secrets come from config_loader."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "conseillers_financiers"
PRESET_LABEL = "Conseillers Financiers (France)"

_LIST_ID = "4a616678-06a0-44d2-a27c-f9248a4c34bf"
_CAMPAIGN_ID = "cb5ce1d8-8a45-47c8-8630-3099dad06e71"

CONSEILLERS_FINANCIERS_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [_LIST_ID],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [_CAMPAIGN_ID],
    "INSTANTLY_PUSH_EVERY": 100,
    "ENRICH_ENABLED": True,
    "ENRICH_BATCH_SIZE": 50,
    "ENRICH_CONCURRENCY": 20,
    "ENRICH_TIMEOUT_MS": 10000,
    "ENRICH_INCLUDED_KEYWORDS": [
        "gestion de patrimoine",
        "conseil en investissement",
        "assurance-vie",
        "assurance vie",
        "transmission",
        "succession",
        "retraite",
        "PER",
        "immobilier locatif",
        "défiscalisation",
        "patrimoine",
        "wealth management",
        "family office",
        "mandataire d'assurance",
        "optimisation patrimoniale",
        "investissement financier",
        "épargne retraite",
        "SCPI",
        "private equity",
        "conseil fiscal",
        "CGP",
        "IFA",
    ],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [
        "agence immobilière",
        "crédit immobilier",
        "courtier prêt",
        "expert-comptable",
        "comptable",
        "notaire",
        "mutuelle",
        "assurance auto",
    ],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [
        "banque",
        "crédit consommation",
        "leasing",
        "location véhicule",
    ],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 6,
    "OUTSCRAPER_LIMIT_PER_QUERY": 30,
    "OUTSCRAPER_POLL_INITIAL_S": 45,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 600,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 8,
    "TARGET_LEADS": 5_000,
    "TARGET_MODE": "instantly_pushed",
    "SERVICE_DEFAULT": "Gestion de Patrimoine",
    "SERVICE_RULES": [
        {"label": "Assurance-Vie", "keywords": ["assurance-vie", "assurance vie", "mandataire d'assurance"]},
        {"label": "Retraite", "keywords": ["retraite", "PER", "épargne retraite", "conseil retraite"]},
        {"label": "Transmission", "keywords": ["transmission", "succession", "transmission de patrimoine", "succession patrimoine"]},
        {"label": "Immobilier Locatif", "keywords": ["immobilier locatif", "SCPI", "défiscalisation"]},
        {"label": "Investissement Financier", "keywords": ["investissement financier", "private equity", "conseil en investissement"]},
    ],
    "KEYWORDS": [
        "conseiller en gestion de patrimoine",
        "cabinet de gestion de patrimoine",
        "CGP",
        "conseiller financier",
        "gestion de patrimoine",
        "conseil en investissement financier",
        "courtier en assurance vie",
        "conseiller en patrimoine",
        "cabinet patrimonial",
        "family office",
        "wealth management",
        "mandataire d'assurance vie",
        "conseiller retraite",
        "optimisation patrimoniale",
        "transmission de patrimoine",
    ],
    "EXPANSION_KEYWORDS": [
        "conseiller indépendant en gestion de patrimoine",
        "IFA",
        "investissement financier",
        "assurance-vie",
        "PER individuel",
        "immobilier locatif",
        "défiscalisation",
        "succession patrimoine",
        "banque privée",
        "gestionnaire de fortune",
        "conseil retraite",
        "épargne retraite",
        "SCPI",
        "private equity",
        "conseil fiscal patrimonial",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": True,
    "PAPPERS_MIN_EMPLOYEES": 10,
    "PAPPERS_ON_UNKNOWN": "reject",
    "PAPPERS_CONCURRENCY": 5,
    "PAPPERS_NAF_PREFIXES": [
        "66.19",
        "66.22",
        "66.30",
        "70.22",
    ],
    "NICHE_METADATA": {
        "angle": "CGP / wealth management / patrimoine.",
        "valeur_client": "",
        "effectif_cible": "10+ salariés",
    },
}

CONFIG = CONSEILLERS_FINANCIERS_CONFIG
