import { SECTEUR_CONFIG } from "@/lib/agence/secteur-config";
import type {
  BudgetKind,
  PrestationType,
  TailleClass,
  TimingClass,
} from "@/lib/admin/funnels/opportunity-card-formulas";
import type { AgencyPresetId } from "@/lib/admin/funnels/sales-preset-scoring";
import contactPool from "@/lib/admin/funnels/contact-pool.json";
import type { Audience } from "@/lib/admin/navigation";
import { isCabinetBuyerSalesAudience, isCifSalesAudience, isComptableSalesAudience } from "@/lib/admin/funnels/sales-audience";

export type { BudgetKind };

export type ServiceId =
  | "web_creation"
  | "ecommerce"
  | "seo"
  | "google_ads"
  | "meta_ads"
  | "dev"
  | "nocode"
  | "shopify"
  | "maintenance"
  | "consulting"
  | "patrimoine_epargne"
  | "tresorerie_entreprise"
  | "retraite_prevoyance"
  | "transmission"
  | "immobilier_scpi"
  | "credit"
  | "assurance"
  | "fiscal_patrimonial"
  | "obligations_declaratives"
  | "conseil_gestion";

export type OperationId =
  | "one_off"
  | "recurring"
  | "redesign"
  | "ecommerce"
  | "acquisition"
  | "seo"
  | "development"
  | "maintenance"
  | "high_value"
  | "tresorerie"
  | "transmission"
  | "retraite"
  | "immobilier"
  | "patrimoine_recurrent";

export type OpportunityCardBlueprint = {
  id: string;
  secteur: string;
  services: ServiceId[];
  operations: OperationId[];
  presetAffinity: AgencyPresetId[];
  prestationType: PrestationType;
  timingClass: TimingClass;
  tailleClass: TailleClass;
  prestation: string;
  historiqueAgences: string;
  zone: string;
  origine?: string;
  companyNameBlurred: string;
  domainBlurred: string;
  contactEmail: string;
  contactPhone: string;
};

export const OFFICIAL_SECTEURS = Object.keys(SECTEUR_CONFIG).filter((key) =>
  [
    "Comptabilité",
    "Conseil financier",
    "Solaire",
    "Pompe à chaleur",
    "Piscines",
    "Rénovation énergétique",
    "Grossiste emballage",
    "Fournitures médicales",
    "Distribution professionnelle",
    "Santé esthétique",
  ].includes(key),
) as string[];

const RAW_BLUEPRINTS: Omit<OpportunityCardBlueprint, "contactEmail" | "contactPhone">[] = [
  // Comptabilité
  {
    id: "bp-compta-ads",
    secteur: "Comptabilité",
    services: ["google_ads", "web_creation"],
    operations: ["acquisition", "one_off"],
    presetAffinity: ["growth", "serial"],
    prestationType: "acquisition_paid",
    timingClass: "fast",
    tailleClass: "tpe",
    prestation: "Campagnes Google Ads locales + pages d'atterrissage sectorielles",
    historiqueAgences: "Cabinet familial — jamais externalisé le digital",
    zone: "Lyon",
    companyNameBlurred: "Cabinet ****",
    domainBlurred: "****.expert",
  },
  {
    id: "bp-compta-seo",
    secteur: "Comptabilité",
    services: ["seo", "web_creation"],
    operations: ["seo", "recurring"],
    presetAffinity: ["growth", "specialist"],
    prestationType: "seo_organique",
    timingClass: "normal",
    tailleClass: "tpe",
    prestation: "Référencement naturel métier + fiches services par expertise",
    historiqueAgences: "Prestataire SEO — résultats trop lents",
    zone: "Nantes",
    companyNameBlurred: "Sarl ****",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-compta-web",
    secteur: "Comptabilité",
    services: ["web_creation", "maintenance"],
    operations: ["one_off", "maintenance"],
    presetAffinity: ["serial"],
    prestationType: "site_vitrine",
    timingClass: "fast",
    tailleClass: "freelancers",
    prestation: "Site vitrine 6 pages + maintenance trimestrielle",
    historiqueAgences: "Site WordPress daté — refonte nécessaire",
    zone: "Bordeaux",
    companyNameBlurred: "**** Conseil",
    domainBlurred: "****.io",
  },
  {
    id: "bp-compta-portal",
    secteur: "Comptabilité",
    services: ["dev", "nocode"],
    operations: ["development", "high_value"],
    presetAffinity: ["architect", "specialist"],
    prestationType: "portail_metier",
    timingClass: "slow",
    tailleClass: "pme_small",
    prestation: "Espace client sécurisé + dépôt documentaire",
    historiqueAgences: "Intégration précédente — périmètre mal cadré",
    zone: "Île-de-France",
    companyNameBlurred: "Groupe ****",
    domainBlurred: "****.com",
  },
  {
    id: "bp-compta-brand",
    secteur: "Comptabilité",
    services: ["web_creation", "consulting"],
    operations: ["redesign", "one_off"],
    presetAffinity: ["premium", "specialist"],
    prestationType: "refonte_site",
    timingClass: "slow",
    tailleClass: "pme_small",
    prestation: "Refonte institutionnelle + charte digitale cabinet",
    historiqueAgences: "Cabinet conseil — livraison partielle non finalisée",
    zone: "Paris",
    companyNameBlurred: "**** & Associés",
    domainBlurred: "****.audit",
  },

  // Conseil financier
  {
    id: "bp-fin-ads",
    secteur: "Conseil financier",
    services: ["google_ads", "meta_ads"],
    operations: ["acquisition", "recurring"],
    presetAffinity: ["growth"],
    prestationType: "acquisition_paid",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "LinkedIn Ads + landing pages patrimoine",
    historiqueAgences: "Agence généraliste — leads peu qualifiés",
    zone: "Paris",
    companyNameBlurred: "**** Patrimoine",
    domainBlurred: "****.private",
  },
  {
    id: "bp-fin-seo",
    secteur: "Conseil financier",
    services: ["seo", "consulting"],
    operations: ["seo", "recurring"],
    presetAffinity: ["growth", "specialist"],
    prestationType: "seo_organique",
    timingClass: "normal",
    tailleClass: "tpe",
    prestation: "Contenus SEO expertise + suivi positions",
    historiqueAgences: "Rédaction interne — manque de bande passante SEO",
    zone: "Remote",
    companyNameBlurred: "**** Finance",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-fin-web",
    secteur: "Conseil financier",
    services: ["web_creation"],
    operations: ["one_off", "redesign"],
    presetAffinity: ["serial"],
    prestationType: "site_vitrine",
    timingClass: "fast",
    tailleClass: "freelancers",
    prestation: "Site one-page premium + formulaire contact qualifié",
    historiqueAgences: "Première collaboration avec une agence web",
    zone: "Nice",
    companyNameBlurred: "**** Conseil",
    domainBlurred: "****.io",
  },
  {
    id: "bp-fin-crm",
    secteur: "Conseil financier",
    services: ["dev", "nocode"],
    operations: ["development"],
    presetAffinity: ["architect"],
    prestationType: "integration_complexe",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Intégration CRM + automatisation relances prospects",
    historiqueAgences: "2 prestataires testés — délais non respectés",
    zone: "Lyon",
    companyNameBlurred: "**** Partners",
    domainBlurred: "****.consulting",
  },
  {
    id: "bp-fin-inbound",
    secteur: "Conseil financier",
    services: ["seo", "google_ads", "web_creation"],
    operations: ["acquisition", "high_value"],
    presetAffinity: ["premium", "growth"],
    prestationType: "acquisition_paid",
    timingClass: "slow",
    tailleClass: "tpe",
    prestation: "Inbound B2B + nurturing contenus patrimoine",
    historiqueAgences: "Équipe marketing interne — besoin d'un partenaire acquisition",
    zone: "Remote / Paris",
    companyNameBlurred: "**** Advisory",
    domainBlurred: "****.wealth",
  },

  // Solaire
  {
    id: "bp-sol-meta",
    secteur: "Solaire",
    services: ["meta_ads", "google_ads"],
    operations: ["acquisition", "recurring"],
    presetAffinity: ["growth"],
    prestationType: "acquisition_paid",
    timingClass: "fast",
    tailleClass: "pme_small",
    prestation: "Meta Ads + retargeting visiteurs installateurs",
    historiqueAgences: "Agence généraliste — coût par lead instable",
    zone: "Toulouse",
    companyNameBlurred: "**** Solaire",
    domainBlurred: "****.energy",
  },
  {
    id: "bp-sol-seo",
    secteur: "Solaire",
    services: ["seo", "web_creation"],
    operations: ["seo", "one_off"],
    presetAffinity: ["growth", "serial"],
    prestationType: "seo_organique",
    timingClass: "normal",
    tailleClass: "tpe",
    prestation: "SEO local + fiches métiers par type d'installation",
    historiqueAgences: "Refonte récente — site peu visible sur les requêtes métier",
    zone: "Marseille",
    companyNameBlurred: "Énergie ****",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-sol-web",
    secteur: "Solaire",
    services: ["web_creation", "maintenance"],
    operations: ["one_off", "redesign"],
    presetAffinity: ["serial"],
    prestationType: "refonte_site",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Refonte site + simulateur économies énergétiques",
    historiqueAgences: "Site daté — refonte nécessaire",
    zone: "Montpellier",
    companyNameBlurred: "**** Solar",
    domainBlurred: "****.com",
  },
  {
    id: "bp-sol-config",
    secteur: "Solaire",
    services: ["dev", "shopify"],
    operations: ["development", "ecommerce"],
    presetAffinity: ["architect"],
    prestationType: "integration_complexe",
    timingClass: "slow",
    tailleClass: "pme_small",
    prestation: "Configurateur technique + intégration CRM",
    historiqueAgences: "Développement interne — projet abandonné",
    zone: "Île-de-France",
    companyNameBlurred: "**** Energie",
    domainBlurred: "****.eu",
  },
  {
    id: "bp-sol-multi",
    secteur: "Solaire",
    services: ["google_ads", "seo"],
    operations: ["acquisition", "recurring"],
    presetAffinity: ["growth", "specialist"],
    prestationType: "acquisition_paid",
    timingClass: "slow",
    tailleClass: "pme_small",
    prestation: "Acquisition multi-régions + reporting hebdomadaire",
    historiqueAgences: "Équipe interne — bande passante insuffisante sur le paid",
    zone: "Lille",
    companyNameBlurred: "Groupe ****",
    domainBlurred: "****.solar",
  },

  // Pompe à chaleur
  {
    id: "bp-pac-ads",
    secteur: "Pompe à chaleur",
    services: ["google_ads", "web_creation"],
    operations: ["acquisition"],
    presetAffinity: ["growth"],
    prestationType: "acquisition_paid",
    timingClass: "fast",
    tailleClass: "tpe",
    prestation: "Google Ads local + pages d'atterrissage par offre",
    historiqueAgences: "Agence locale — suivi insuffisant",
    zone: "Strasbourg",
    companyNameBlurred: "**** Thermique",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-pac-seo",
    secteur: "Pompe à chaleur",
    services: ["seo"],
    operations: ["seo", "recurring"],
    presetAffinity: ["growth"],
    prestationType: "seo_organique",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Référencement local + contenus aides MaPrimeRénov'",
    historiqueAgences: "Contenus rédigés en interne — SEO non structuré",
    zone: "Rennes",
    companyNameBlurred: "Install ****",
    domainBlurred: "****.pro",
  },
  {
    id: "bp-pac-web",
    secteur: "Pompe à chaleur",
    services: ["web_creation"],
    operations: ["one_off", "redesign"],
    presetAffinity: ["serial"],
    prestationType: "site_vitrine",
    timingClass: "fast",
    tailleClass: "tpe",
    prestation: "Site vitrine 8 pages + formulaire contact qualifié",
    historiqueAgences: "Maintenance externalisée — besoin de continuité",
    zone: "Grenoble",
    companyNameBlurred: "SAS ****",
    domainBlurred: "****.com",
  },
  {
    id: "bp-pac-funnel",
    secteur: "Pompe à chaleur",
    services: ["web_creation", "dev"],
    operations: ["development", "one_off"],
    presetAffinity: ["architect", "specialist"],
    prestationType: "integration_complexe",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Tunnel de qualification + intégration CRM chantier",
    historiqueAgences: "Refonte précédente — site non adapté mobile",
    zone: "Lyon",
    companyNameBlurred: "**** Bâtiment",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-pac-maint",
    secteur: "Pompe à chaleur",
    services: ["maintenance", "web_creation"],
    operations: ["maintenance", "recurring"],
    presetAffinity: ["serial"],
    prestationType: "maintenance",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Maintenance site + mises à jour contenus saisonniers",
    historiqueAgences: "Freelance précédent — disponibilité irrégulière",
    zone: "Nantes",
    companyNameBlurred: "**** Chauffage",
    domainBlurred: "****.energy",
  },

  // Piscines
  {
    id: "bp-pisc-web",
    secteur: "Piscines",
    services: ["web_creation", "maintenance"],
    operations: ["one_off", "maintenance"],
    presetAffinity: ["serial"],
    prestationType: "site_vitrine",
    timingClass: "fast",
    tailleClass: "tpe",
    prestation: "Site vitrine 8 pages + formulaire contact qualifié",
    historiqueAgences: "Site vieillissant — navigation peu claire",
    zone: "Aix-en-Provence",
    companyNameBlurred: "Piscines ****",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-pisc-ads",
    secteur: "Piscines",
    services: ["meta_ads", "google_ads"],
    operations: ["acquisition", "recurring"],
    presetAffinity: ["growth"],
    prestationType: "acquisition_paid",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Campagnes saisonnières Meta + Google Ads local",
    historiqueAgences: "Campagnes internes — budget mal réparti",
    zone: "Cannes",
    companyNameBlurred: "**** Pool",
    domainBlurred: "****.com",
  },
  {
    id: "bp-pisc-book",
    secteur: "Piscines",
    services: ["web_creation", "dev"],
    operations: ["development", "one_off"],
    presetAffinity: ["architect"],
    prestationType: "integration_complexe",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Réservation en ligne + paiement acompte Stripe",
    historiqueAgences: "Agence e-commerce — manque d'expertise métier",
    zone: "Toulon",
    companyNameBlurred: "**** Aqua",
    domainBlurred: "****.shop",
  },
  {
    id: "bp-pisc-seo",
    secteur: "Piscines",
    services: ["seo"],
    operations: ["seo", "recurring"],
    presetAffinity: ["growth"],
    prestationType: "seo_organique",
    timingClass: "normal",
    tailleClass: "tpe",
    prestation: "SEO local + pages entretien et rénovation",
    historiqueAgences: "Agence précédente — non conforme RGPD",
    zone: "Biarritz",
    companyNameBlurred: "**** Piscine",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-pisc-redesign",
    secteur: "Piscines",
    services: ["web_creation", "ecommerce"],
    operations: ["redesign", "ecommerce"],
    presetAffinity: ["serial", "specialist"],
    prestationType: "refonte_site",
    timingClass: "slow",
    tailleClass: "pme_small",
    prestation: "Refonte catalogue produits + module showroom",
    historiqueAgences: "Prestataire national — manque de suivi local",
    zone: "Perpignan",
    companyNameBlurred: "Maison ****",
    domainBlurred: "****.pool",
  },

  // Rénovation énergétique
  {
    id: "bp-renov-ads",
    secteur: "Rénovation énergétique",
    services: ["google_ads", "meta_ads"],
    operations: ["acquisition", "recurring"],
    presetAffinity: ["growth"],
    prestationType: "acquisition_paid",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Campagnes multi-régions + reporting mensuel",
    historiqueAgences: "Agence précédente — coût par lead trop élevé",
    zone: "Lille",
    companyNameBlurred: "**** Rénov",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-renov-seo",
    secteur: "Rénovation énergétique",
    services: ["seo", "web_creation"],
    operations: ["seo"],
    presetAffinity: ["growth", "serial"],
    prestationType: "seo_organique",
    timingClass: "normal",
    tailleClass: "tpe",
    prestation: "Contenus SEO isolation + suivi positions locales",
    historiqueAgences: "Rédaction ponctuelle — pas de stratégie SEO",
    zone: "Rouen",
    companyNameBlurred: "Isolation ****",
    domainBlurred: "****.pro",
  },
  {
    id: "bp-renov-web",
    secteur: "Rénovation énergétique",
    services: ["web_creation"],
    operations: ["one_off", "redesign"],
    presetAffinity: ["serial"],
    prestationType: "refonte_site",
    timingClass: "fast",
    tailleClass: "pme_small",
    prestation: "Refonte site + pages aides et subventions",
    historiqueAgences: "Site non responsive — perte mobile importante",
    zone: "Dijon",
    companyNameBlurred: "**** Énergie",
    domainBlurred: "****.com",
  },
  {
    id: "bp-renov-crm",
    secteur: "Rénovation énergétique",
    services: ["dev", "nocode"],
    operations: ["development"],
    presetAffinity: ["architect", "specialist"],
    prestationType: "integration_complexe",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "CRM chantier + suivi dossiers MaPrimeRénov'",
    historiqueAgences: "Intégration ERP précédente échouée",
    zone: "Île-de-France",
    companyNameBlurred: "**** Travaux",
    domainBlurred: "****.eu",
  },
  {
    id: "bp-renov-leads",
    secteur: "Rénovation énergétique",
    services: ["google_ads", "web_creation"],
    operations: ["acquisition", "high_value"],
    presetAffinity: ["growth", "premium"],
    prestationType: "acquisition_paid",
    timingClass: "slow",
    tailleClass: "pme_small",
    prestation: "Génération leads B2B + nurturing artisans partenaires",
    historiqueAgences: "Équipe commerciale — manque de leads digitaux",
    zone: "Remote",
    companyNameBlurred: "Groupe ****",
    domainBlurred: "****.reno",
  },

  // Grossiste emballage
  {
    id: "bp-gross-web",
    secteur: "Grossiste emballage",
    services: ["web_creation", "ecommerce"],
    operations: ["one_off", "ecommerce"],
    presetAffinity: ["serial", "architect"],
    prestationType: "ecommerce_build",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Refonte catalogue produits + hébergement managé",
    historiqueAgences: "Migration catalogue digital — projet en pause",
    zone: "Lyon",
    companyNameBlurred: "**** Emballage",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-gross-shopify",
    secteur: "Grossiste emballage",
    services: ["shopify", "ecommerce"],
    operations: ["ecommerce", "development"],
    presetAffinity: ["architect"],
    prestationType: "ecommerce_build",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Migration Shopify + connecteur ERP stocks",
    historiqueAgences: "Agence e-commerce — manque d'expertise Shopify",
    zone: "Lille",
    companyNameBlurred: "Maison ****",
    domainBlurred: "****.shop",
  },
  {
    id: "bp-gross-seo",
    secteur: "Grossiste emballage",
    services: ["seo"],
    operations: ["seo", "recurring"],
    presetAffinity: ["growth"],
    prestationType: "seo_organique",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Référencement naturel catalogue B2B + contenus experts",
    historiqueAgences: "Expansion export — visibilité insuffisante",
    zone: "Remote",
    companyNameBlurred: "**** Pack",
    domainBlurred: "****.com",
  },
  {
    id: "bp-gross-ads",
    secteur: "Grossiste emballage",
    services: ["google_ads"],
    operations: ["acquisition"],
    presetAffinity: ["growth"],
    prestationType: "acquisition_paid",
    timingClass: "fast",
    tailleClass: "pme_medium",
    prestation: "Google Ads B2B + landing pages par gamme",
    historiqueAgences: "Campagne commerciale — acquisition non rentable",
    zone: "Strasbourg",
    companyNameBlurred: "Transports ****",
    domainBlurred: "****.log",
  },
  {
    id: "bp-gross-maint",
    secteur: "Grossiste emballage",
    services: ["maintenance", "web_creation"],
    operations: ["maintenance", "recurring"],
    presetAffinity: ["serial"],
    prestationType: "maintenance",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Maintenance e-commerce + mises à jour catalogue",
    historiqueAgences: "Sous-traitance ponctuelle — besoin de continuité",
    zone: "Nantes",
    companyNameBlurred: "**** Studio",
    domainBlurred: "****.shop",
  },

  // Fournitures médicales
  {
    id: "bp-med-seo",
    secteur: "Fournitures médicales",
    services: ["seo", "web_creation"],
    operations: ["seo", "recurring"],
    presetAffinity: ["growth", "specialist"],
    prestationType: "seo_organique",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Contenus SEO catalogue B2B + fiches produits",
    historiqueAgences: "Rédaction technique — manque de compétences SEO",
    zone: "Remote",
    companyNameBlurred: "**** Med",
    domainBlurred: "****.health",
  },
  {
    id: "bp-med-portal",
    secteur: "Fournitures médicales",
    services: ["dev", "nocode"],
    operations: ["development", "high_value"],
    presetAffinity: ["architect", "specialist"],
    prestationType: "portail_metier",
    timingClass: "slow",
    tailleClass: "pme_medium",
    prestation: "Portail commandes B2B + authentification clients",
    historiqueAgences: "Refonte datée — non conforme accessibilité",
    zone: "Île-de-France",
    companyNameBlurred: "**** Santé",
    domainBlurred: "****.med",
  },
  {
    id: "bp-med-ads",
    secteur: "Fournitures médicales",
    services: ["google_ads", "meta_ads"],
    operations: ["acquisition"],
    presetAffinity: ["growth"],
    prestationType: "acquisition_paid",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "LinkedIn Ads + landing pages professionnels santé",
    historiqueAgences: "Première collaboration avec une agence web",
    zone: "Lyon",
    companyNameBlurred: "**** Pharma",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-med-web",
    secteur: "Fournitures médicales",
    services: ["web_creation"],
    operations: ["one_off", "redesign"],
    presetAffinity: ["serial"],
    prestationType: "refonte_site",
    timingClass: "fast",
    tailleClass: "pme_small",
    prestation: "Refonte site institutionnel + espace ressources",
    historiqueAgences: "Agence généraliste — manque d'expertise métier",
    zone: "Toulouse",
    companyNameBlurred: "Clinique ****",
    domainBlurred: "****.care",
  },
  {
    id: "bp-med-track",
    secteur: "Fournitures médicales",
    services: ["dev", "google_ads"],
    operations: ["development", "acquisition"],
    presetAffinity: ["architect", "growth"],
    prestationType: "acquisition_paid",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Tracking conversions + campagnes Google Ads B2B",
    historiqueAgences: "2 agences testées — tracking insuffisant",
    zone: "Remote",
    companyNameBlurred: "**** Formation",
    domainBlurred: "****.org",
  },

  // Distribution professionnelle
  {
    id: "bp-dist-web",
    secteur: "Distribution professionnelle",
    services: ["web_creation", "maintenance"],
    operations: ["one_off", "maintenance"],
    presetAffinity: ["serial"],
    prestationType: "site_vitrine",
    timingClass: "fast",
    tailleClass: "pme_small",
    prestation: "Landing pages par gamme + hébergement managé",
    historiqueAgences: "Pages statiques — mise à jour difficile",
    zone: "Lille",
    companyNameBlurred: "**** Distrib",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-dist-ads",
    secteur: "Distribution professionnelle",
    services: ["google_ads"],
    operations: ["acquisition", "recurring"],
    presetAffinity: ["growth"],
    prestationType: "acquisition_paid",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Google Ads + tracking conversions B2B",
    historiqueAgences: "Agence locale — insatisfait du suivi",
    zone: "Marseille",
    companyNameBlurred: "Agence ****",
    domainBlurred: "****.pro",
  },
  {
    id: "bp-dist-seo",
    secteur: "Distribution professionnelle",
    services: ["seo"],
    operations: ["seo"],
    presetAffinity: ["growth"],
    prestationType: "seo_organique",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "SEO local + contenus organiques par région",
    historiqueAgences: "Contenus ponctuels — pas de ligne éditoriale",
    zone: "Bordeaux",
    companyNameBlurred: "**** Logistique",
    domainBlurred: "****.eu",
  },
  {
    id: "bp-dist-erp",
    secteur: "Distribution professionnelle",
    services: ["dev", "shopify"],
    operations: ["development", "ecommerce"],
    presetAffinity: ["architect"],
    prestationType: "portail_metier",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Portail client + intégration ERP",
    historiqueAgences: "Intégration ERP précédente échouée",
    zone: "Île-de-France",
    companyNameBlurred: "**** Logistics",
    domainBlurred: "****.com",
  },
  {
    id: "bp-dist-leads",
    secteur: "Distribution professionnelle",
    services: ["google_ads", "web_creation"],
    operations: ["acquisition"],
    presetAffinity: ["growth", "specialist"],
    prestationType: "site_vitrine",
    timingClass: "normal",
    tailleClass: "pme_medium",
    prestation: "Site + génération de leads B2B",
    historiqueAgences: "Changement de locaux — refonte identité en cours",
    zone: "Strasbourg",
    companyNameBlurred: "Transports ****",
    domainBlurred: "****.log",
  },

  // Santé esthétique
  {
    id: "bp-esth-ads",
    secteur: "Santé esthétique",
    services: ["meta_ads", "google_ads"],
    operations: ["acquisition", "recurring"],
    presetAffinity: ["growth"],
    prestationType: "acquisition_paid",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Meta Ads + campagnes locales par établissement",
    historiqueAgences: "Prestataire national — manque de suivi local",
    zone: "Toulouse",
    companyNameBlurred: "Groupe ****",
    domainBlurred: "****.sante",
  },
  {
    id: "bp-esth-web",
    secteur: "Santé esthétique",
    services: ["web_creation", "dev"],
    operations: ["one_off", "development"],
    presetAffinity: ["serial", "architect"],
    prestationType: "site_vitrine",
    timingClass: "fast",
    tailleClass: "freelancers",
    prestation: "Site one-page premium + module prise de rendez-vous",
    historiqueAgences: "Nouveau gérant — refonte identité en cours",
    zone: "Paris",
    companyNameBlurred: "Clinique ****",
    domainBlurred: "****.aesthetic",
  },
  {
    id: "bp-esth-seo",
    secteur: "Santé esthétique",
    services: ["seo"],
    operations: ["seo", "recurring"],
    presetAffinity: ["growth"],
    prestationType: "seo_organique",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "SEO local + pages traitements par spécialité",
    historiqueAgences: "Agence précédente — contenus non conformes",
    zone: "Nice",
    companyNameBlurred: "**** Esthétique",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-esth-parcours",
    secteur: "Santé esthétique",
    services: ["web_creation", "consulting"],
    operations: ["redesign", "high_value"],
    presetAffinity: ["specialist", "premium"],
    prestationType: "acquisition_paid",
    timingClass: "slow",
    tailleClass: "pme_small",
    prestation: "Parcours patient + campagnes locales",
    historiqueAgences: "Refonte datée — parcours patient fragmenté",
    zone: "Lyon",
    companyNameBlurred: "**** Imagerie",
    domainBlurred: "****.med",
  },
  {
    id: "bp-esth-brand",
    secteur: "Santé esthétique",
    services: ["web_creation", "meta_ads"],
    operations: ["redesign", "acquisition"],
    presetAffinity: ["serial", "growth"],
    prestationType: "refonte_site",
    timingClass: "fast",
    tailleClass: "tpe",
    prestation: "Refonte identité digitale + lancement réseaux",
    historiqueAgences: "Croissance commerciale — image datée",
    zone: "Bordeaux",
    companyNameBlurred: "**** Beauty",
    domainBlurred: "****.co",
  },
];

export const OPPORTUNITY_CARD_BLUEPRINTS: OpportunityCardBlueprint[] = RAW_BLUEPRINTS.map(
  (bp, i) => ({
    ...bp,
    contactEmail: contactPool[i % contactPool.length].email,
    contactPhone: contactPool[i % contactPool.length].phone,
  }),
);

const COMPTABLE_RAW_BLUEPRINTS: Omit<
  OpportunityCardBlueprint,
  "contactEmail" | "contactPhone"
>[] = [
  {
    id: "bp-ec-restauration",
    secteur: "Restauration",
    services: ["web_creation", "google_ads"],
    operations: ["one_off", "recurring"],
    presetAffinity: ["serial", "growth"],
    prestationType: "tenue_comptable",
    timingClass: "fast",
    tailleClass: "tpe",
    prestation: "Reprise tenue + déclarations TVA — brasserie 12 couverts",
    historiqueAgences: "Gestion interne — dirigeant saturé",
    zone: "Lyon",
    origine: "Saison estivale",
    companyNameBlurred: "Brasserie ****",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-ec-artisanat",
    secteur: "Artisanat",
    services: ["google_ads", "maintenance"],
    operations: ["recurring", "one_off"],
    presetAffinity: ["serial", "specialist"],
    prestationType: "fiscal_liasse",
    timingClass: "normal",
    tailleClass: "tpe",
    prestation: "Liasse fiscale + TVA — artisan BTP local",
    historiqueAgences: "Expert-comptable indépendant — départ retraite",
    zone: "Nantes",
    origine: "Passage micro → réel",
    companyNameBlurred: "Sarl ****",
    domainBlurred: "****.artisan",
  },
  {
    id: "bp-ec-btp",
    secteur: "BTP / rénovation",
    services: ["seo", "web_creation"],
    operations: ["recurring"],
    presetAffinity: ["growth", "serial"],
    prestationType: "social_paie",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Mission social / paie récurrente — structure en croissance",
    historiqueAgences: "Gestion interne — charge sociale croissante",
    zone: "Bordeaux",
    origine: "Marchés publics remportés",
    companyNameBlurred: "**** BTP",
    domainBlurred: "****.pro",
  },
  {
    id: "bp-ec-ecommerce",
    secteur: "E-commerce",
    services: ["ecommerce", "web_creation"],
    operations: ["recurring", "one_off"],
    presetAffinity: ["growth", "architect"],
    prestationType: "tenue_comptable",
    timingClass: "fast",
    tailleClass: "tpe",
    prestation: "Tenue e-commerce + TVA marketplace — boutique en ligne",
    historiqueAgences: "Cabinet précédent — suivi insuffisant",
    zone: "Paris",
    origine: "Croissance CA",
    companyNameBlurred: "**** Shop",
    domainBlurred: "****.store",
  },
  {
    id: "bp-ec-sante",
    secteur: "Santé libérale",
    services: ["consulting", "google_ads"],
    operations: ["one_off", "high_value"],
    presetAffinity: ["premium", "specialist"],
    prestationType: "reprise_dossier",
    timingClass: "slow",
    tailleClass: "freelancers",
    prestation: "Reprise dossier structuré + obligations fiscales — profession libérale",
    historiqueAgences: "Première externalisation comptable",
    zone: "Île-de-France",
    origine: "Recrutement salariés",
    companyNameBlurred: "Cabinet ****",
    domainBlurred: "****.med",
  },
];

export const COMPTABLE_OPPORTUNITY_CARD_BLUEPRINTS: OpportunityCardBlueprint[] =
  COMPTABLE_RAW_BLUEPRINTS.map((bp, i) => ({
    ...bp,
    contactEmail: contactPool[i % contactPool.length].email,
    contactPhone: contactPool[i % contactPool.length].phone,
  }));

const CIF_RAW_BLUEPRINTS: Omit<
  OpportunityCardBlueprint,
  "contactEmail" | "contactPhone"
>[] = [
  {
    id: "bp-cif-restauration",
    secteur: "Restauration",
    services: ["tresorerie_entreprise", "patrimoine_epargne"],
    operations: ["recurring", "tresorerie"],
    presetAffinity: ["serial", "growth"],
    prestationType: "tresorerie_entreprise",
    timingClass: "fast",
    tailleClass: "tpe",
    prestation: "Mandat trésorerie + placement cash — brasserie 12 couverts",
    historiqueAgences: "Banque privée — suivi trésorerie insuffisant",
    zone: "Lyon",
    origine: "Croissance CA",
    companyNameBlurred: "Brasserie ****",
    domainBlurred: "****.fr",
  },
  {
    id: "bp-cif-artisanat",
    secteur: "Artisanat",
    services: ["transmission", "fiscal_patrimonial"],
    operations: ["transmission", "one_off"],
    presetAffinity: ["serial", "specialist"],
    prestationType: "transmission",
    timingClass: "normal",
    tailleClass: "tpe",
    prestation: "Transmission entreprise — Dutreil / holding — artisan BTP",
    historiqueAgences: "CGP réseau — pas d'ingénierie transmission",
    zone: "Nantes",
    origine: "Cession / transmission d'entreprise",
    companyNameBlurred: "Sarl ****",
    domainBlurred: "****.artisan",
  },
  {
    id: "bp-cif-btp",
    secteur: "BTP / rénovation",
    services: ["tresorerie_entreprise", "conseil_gestion"],
    operations: ["recurring", "tresorerie"],
    presetAffinity: ["growth", "serial"],
    prestationType: "tresorerie_entreprise",
    timingClass: "normal",
    tailleClass: "pme_small",
    prestation: "Placement trésorerie excédentaire — structure en croissance",
    historiqueAgences: "Compte courant bloqué — cash-flow à structurer",
    zone: "Bordeaux",
    origine: "Besoin de cash-flow / placement de trésorerie",
    companyNameBlurred: "**** BTP",
    domainBlurred: "****.pro",
  },
  {
    id: "bp-cif-conseil",
    secteur: "Conseil financier",
    services: ["patrimoine_epargne", "fiscal_patrimonial"],
    operations: ["recurring", "patrimoine_recurrent"],
    presetAffinity: ["growth", "specialist"],
    prestationType: "patrimoine_epargne",
    timingClass: "fast",
    tailleClass: "tpe",
    prestation: "Structuration patrimoine dirigeant — PER, AV, épargne",
    historiqueAgences: "Premier externalisation conseil patrimonial",
    zone: "Paris",
    origine: "Création / transmission de patrimoine",
    companyNameBlurred: "**** Conseil",
    domainBlurred: "****.finance",
  },
  {
    id: "bp-cif-sante",
    secteur: "Santé libérale",
    services: ["retraite_prevoyance", "patrimoine_epargne"],
    operations: ["recurring", "retraite"],
    presetAffinity: ["premium", "specialist"],
    prestationType: "retraite_prevoyance",
    timingClass: "slow",
    tailleClass: "freelancers",
    prestation: "Retraite / prévoyance dirigeant — PER, Madelin, assurance-vie",
    historiqueAgences: "Banque — pas de suivi retraite structuré",
    zone: "Île-de-France",
    origine: "Retraite / prévoyance du dirigeant",
    companyNameBlurred: "Cabinet ****",
    domainBlurred: "****.med",
  },
];

export const CIF_OPPORTUNITY_CARD_BLUEPRINTS: OpportunityCardBlueprint[] =
  CIF_RAW_BLUEPRINTS.map((bp, i) => ({
    ...bp,
    contactEmail: contactPool[i % contactPool.length].email,
    contactPhone: contactPool[i % contactPool.length].phone,
  }));

export function getOpportunityCardBlueprints(
  audience: Audience = "agence",
): OpportunityCardBlueprint[] {
  if (isCifSalesAudience(audience)) {
    return CIF_OPPORTUNITY_CARD_BLUEPRINTS;
  }
  if (isComptableSalesAudience(audience)) {
    return COMPTABLE_OPPORTUNITY_CARD_BLUEPRINTS;
  }

  return OPPORTUNITY_CARD_BLUEPRINTS;
}
