import type { SalesQuestion } from "./sales-questions";

export const AGENCE_OBJECTIFS_QUESTIONS: SalesQuestion[] = [
  {
    id: "o1",
    number: 1,
    sectionId: "objectifs",
    type: "multi",
    maxSelections: 2,
    prompt:
      "Quelle est aujourd'hui votre principale difficulté pour développer votre activité ?",
    description: "Sélectionnez jusqu'à 2 réponses.",
    options: [
      { id: "qualified_leads", label: "Manque de demandes entrantes qualifiées" },
      { id: "irregular_pipeline", label: "Pipeline irrégulier / saisonnier" },
      { id: "low_conversion", label: "Taux de conversion faible sur les leads existants" },
      { id: "bench_time", label: "Équipe sous-utilisée (bench time)" },
      { id: "hiring_skills", label: "Difficulté à recruter ou monter en compétences" },
      { id: "key_clients", label: "Forte dépendance à 1–2 gros clients" },
    ],
  },
  {
    id: "o2",
    number: 2,
    sectionId: "objectifs",
    type: "single",
    prompt: "Avez-vous actuellement de la capacité pour prendre de nouveaux projets ?",
    options: [
      { id: "high", label: "Oui, capacité significative (≥ 3 projets/mois)" },
      { id: "moderate", label: "Oui, capacité modérée (1–2 projets/mois)" },
      { id: "limited", label: "Capacité limitée sur certains types de projets" },
      { id: "saturated", label: "Non, équipe saturée" },
      { id: "variable", label: "Variable selon le trimestre" },
    ],
  },
  {
    id: "o3",
    number: 3,
    sectionId: "objectifs",
    type: "single",
    prompt: "Quelle est la principale raison de cette situation ?",
    options: [
      { id: "insufficient_leads", label: "Flux de leads insuffisant" },
      { id: "unqualified_leads", label: "Leads non qualifiés / hors cible" },
      { id: "slow_sales", label: "Processus commercial trop lent" },
      { id: "hard_to_sell", label: "Positionnement ou offre difficile à vendre" },
      { id: "high_prices", label: "Prix perçus trop élevés" },
      { id: "missing_skills", label: "Compétences ou ressources manquantes en interne" },
      { id: "full_capacity", label: "Équipe déjà à pleine charge" },
    ],
  },
  {
    id: "o4",
    number: 4,
    sectionId: "objectifs",
    type: "multi",
    maxSelections: 3,
    prompt: "Qu'est-ce qui fait que cette capacité n'est pas remplie aujourd'hui ?",
    description: "Sélectionnez jusqu'à 3 réponses.",
    options: [
      { id: "no_prospecting", label: "Pas assez de prospection active" },
      { id: "weak_channels", label: "Canaux d'acquisition peu performants" },
      { id: "weak_network", label: "Bouche-à-oreille / réseau insuffisant" },
      { id: "offer_mismatch", label: "Offre pas adaptée au marché" },
      { id: "low_visibility", label: "Manque de visibilité / notoriété" },
      { id: "price_competition", label: "Concurrence agressive sur les prix" },
      { id: "no_sales_resource", label: "Ressources commerciales insuffisantes" },
    ],
  },
  {
    id: "o5",
    number: 5,
    sectionId: "objectifs",
    type: "multi",
    maxSelections: 3,
    prompt: "Qu'avez-vous déjà essayé pour remplir cette capacité ?",
    description: "Sélectionnez jusqu'à 3 réponses.",
    options: [
      { id: "direct_prospecting", label: "Prospection directe (email, LinkedIn, appels)" },
      { id: "paid_ads", label: "Publicité payante (Google, Meta)" },
      { id: "seo_content", label: "SEO / content marketing" },
      { id: "partnerships", label: "Partenariats / apporteurs d'affaires" },
      { id: "sales_hiring", label: "Recrutement commercial" },
      { id: "platforms", label: "Plateformes / marketplaces" },
      { id: "nothing_structured", label: "Rien de structuré jusqu'ici" },
    ],
  },
  {
    id: "o6",
    number: 6,
    sectionId: "objectifs",
    type: "single",
    prompt:
      "Quel écart observez-vous entre votre scénario idéal (activité à pleine capacité) et votre réalité actuelle ?",
    options: [
      { id: "major_gap", label: "Écart majeur : moins de 30 % de la capacité cible" },
      { id: "significant_gap", label: "Écart significatif : 30–60 %" },
      { id: "moderate_gap", label: "Écart modéré : 60–85 %" },
      { id: "near_target", label: "Proche de l'objectif (> 85 %)" },
      { id: "at_capacity", label: "Déjà à pleine capacité" },
      { id: "no_vision", label: "Pas de vision chiffrée / objectif flou" },
    ],
  },
];
