import type { SalesQuestion } from "./sales-questions";

export const CIF_OBJECTIFS_QUESTIONS: SalesQuestion[] = [
  {
    id: "o2",
    number: 1,
    sectionId: "objectifs",
    type: "single",
    prompt: "Avez-vous actuellement de la capacité pour prendre de nouveaux mandats {clientSegment} ?",
    options: [
      { id: "high", label: "Oui, capacité significative (≥ 5 mandats/mois)" },
      { id: "moderate", label: "Oui, capacité modérée (2–4 mandats/mois)" },
      { id: "limited", label: "Capacité limitée sur certains types de missions" },
      { id: "saturated", label: "Non, cabinet saturé" },
      { id: "variable", label: "Variable selon la période (signaux, clôtures fiscales)" },
    ],
  },
  {
    id: "o3",
    number: 2,
    sectionId: "objectifs",
    type: "single",
    prompt: "Pourquoi êtes-vous à cette capacité aujourd'hui ?",
    options: [
      { id: "insufficient_prospects", label: "Flux de prospects insuffisant" },
      { id: "unqualified_prospects", label: "Prospects non qualifiés (hors zone, honoraires, typologie)" },
      { id: "slow_onboarding", label: "Processus de prise en charge trop long (KYC, mandat)" },
      { id: "hard_to_sell", label: "Offre / honoraires difficiles à vendre" },
      { id: "missing_skills", label: "Manque de compétences sur certaines missions" },
      { id: "full_capacity", label: "Équipe déjà à pleine charge" },
    ],
  },
  {
    id: "o4",
    number: 3,
    sectionId: "objectifs",
    type: "multi",
    maxSelections: 3,
    prompt: "Qu'est-ce qui vous freine pour remplir davantage cette capacité ?",
    description: "Sélectionnez jusqu'à 3 réponses.",
    options: [
      { id: "no_local_prospecting", label: "Pas assez de prospection locale" },
      { id: "weak_channels", label: "Canaux d'acquisition peu performants" },
      { id: "weak_network", label: "Bouche-à-oreille / réseau insuffisant" },
      { id: "offer_mismatch", label: "Offre pas adaptée aux {clientSegment} de votre zone" },
      { id: "low_visibility", label: "Manque de visibilité (site, avis, réseaux)" },
      { id: "fee_competition", label: "Concurrence agressive des banques / réseaux sur les honoraires" },
      { id: "no_acquisition_resource", label: "Pas de ressource dédiée à l'acquisition" },
    ],
  },
  {
    id: "o5",
    number: 4,
    sectionId: "objectifs",
    type: "multi",
    maxSelections: 3,
    prompt: "Qu'avez-vous déjà essayé pour remplir cette capacité ?",
    description: "Sélectionnez jusqu'à 3 réponses.",
    options: [
      { id: "direct_prospecting", label: "Prospection directe (email, LinkedIn, appels)" },
      { id: "local_ads", label: "Publicité locale (Google, Meta)" },
      { id: "partnerships", label: "Partenariats (experts-comptables, notaires, avocats)" },
      { id: "events", label: "Événements / réseaux locaux" },
      { id: "sales_hiring", label: "Recrutement d'un profil commercial" },
      { id: "directories", label: "Plateformes / annuaires" },
      { id: "nothing_structured", label: "Rien de structuré jusqu'ici" },
    ],
  },
  {
    id: "o6",
    number: 5,
    sectionId: "objectifs",
    type: "single",
    prompt:
      "Quel écart observez-vous entre votre scénario idéal (cabinet à pleine capacité) et votre réalité actuelle ?",
    options: [
      { id: "major_gap", label: "Écart majeur : moins de 30 % de la capacité cible" },
      { id: "significant_gap", label: "Écart significatif : 30–60 %" },
      { id: "moderate_gap", label: "Écart modéré : 60–85 %" },
      { id: "near_target", label: "Proche de l'objectif (> 85 %)" },
      { id: "at_capacity", label: "Déjà à pleine capacité" },
      { id: "no_vision", label: "Pas de vision chiffrée / objectif flou" },
    ],
  },
  {
    id: "o1",
    number: 6,
    sectionId: "objectifs",
    type: "multi",
    maxSelections: 2,
    prompt:
      "En synthèse, quelles difficultés rencontrez-vous le plus dans le développement de votre portefeuille de mandats {clientSegment} ?",
    description: "Sélectionnez jusqu'à 2 réponses.",
    options: [
      { id: "qualified_dossiers", label: "Manque de nouveaux mandats qualifiés" },
      { id: "aging_portfolio", label: "Portefeuille vieillissant / turnover client" },
      { id: "underused_team", label: "Équipe sous-utilisée" },
      { id: "hiring", label: "Difficulté à recruter des conseillers" },
      { id: "key_dossiers", label: "Forte dépendance à quelques gros encours" },
      { id: "bank_competition", label: "Concurrence des banques privées / robo-advisors" },
    ],
  },
];
