export {
  LEGACY_CGV_FILENAMES,
  LEGACY_TECH_STACK_DOC_DIR,
  LEGAL_DOCUMENTATION_ROOT,
  SITE_CONTENT_ROOT,
  SITE_TECH_DIR,
  TECH_CONTENT_DIR,
  cgvMarkdownPath,
  faqJsonPath,
  getSharedCvgMarkdownPath,
  jumFaqJsonPath,
  legalDocumentationNicheDir,
  pricingJsonPath,
  sequenceMarkdownPath,
  sequencesDir,
  sharedLegalDocPath,
  type LegalDocKind,
  type LegalDocumentationNiche,
  type SharedLegalDocKind,
} from "@/app/(marketing)/content/paths";
