"""JUM Advisory outreach preset — static rules; secrets come from config_loader."""

PRESET_ID = "jum_advisory"
PRESET_LABEL = "JUM Advisory (outreach Béatrice Meyer)"

# One Instantly campaign + list per vertical (mirrors lib/admin/niches/jum-verticals.ts)
# Terrassement = BTP; TEMP - BTP list / BTP PME campaign are excluded.
# New liberal profession verticals get list/campaign IDs filled by provision-instantly.
JUM_VERTICALS = [
    {
        "key": "restaurant",
        "label": "Restaurant",
        "segment": "restaurant",
        "list_id": "8ad641e7-3456-42df-9281-2c11f97df1c5",
        "campaign_id": "e4f11e76-717e-4be9-a6ad-c7f0a331afb7",
        "list_name": "TEMP - RESTAURANT",
        "campaign_name": "Hercule — Restaurants indépendants (France)",
        "calendly_url": "https://calendly.com/jum-advisory/rentabilite-restaurant",
    },
    {
        "key": "btp",
        "label": "Terrassement / BTP",
        "segment": "b2b",
        "list_id": "d4bc89f7-b271-4ed7-9539-4ac968bfb7c9",
        "campaign_id": "05bc06f8-4f60-4e6c-bae1-7afe30df38c7",
        "list_name": "TEMP - TERRASSEMENT",
        "campaign_name": "Hercule — Terrassement / VRD (France)",
        "calendly_url": "https://calendly.com/jum-advisory/rendez-vous-comptable-btp",
    },
    {
        "key": "dentiste",
        "label": "Dentiste",
        "segment": "dentiste",
        "list_id": "c4eb10d7-2285-4fc3-aa06-3230d2498d8e",
        "campaign_id": "0f0b450a-e550-461c-96f6-1a7681678d67",
        "list_name": "TEMP - DENTISTE",
        "campaign_name": "Hercule — Chirurgiens-dentistes (France)",
        "calendly_url": "https://calendly.com/jum-advisory/rendez-vous-comptable-dentiste",
    },
    {
        "key": "medecin",
        "label": "Médecin généraliste",
        "segment": "medecin",
        "list_id": "7e3b619f-9823-4d64-bc50-31f01bb08e6d",
        "campaign_id": "5c142a13-fcdf-4d6d-92e7-2afbc1865a5a",
        "list_name": "Hercule — Médecins généralistes (France)",
        "campaign_name": "Médecins (CIF)",
        "calendly_url": "https://calendly.com/jum-advisory/rendez-vous-comptable-medecin",
    },
    {
        "key": "kine",
        "label": "Kinésithérapeute",
        "segment": "kine",
        "list_id": "2a45b863-c705-4116-acec-31f49857bbbb",
        "campaign_id": "581b9357-753e-4c6e-aa99-d8b36fefca2d",
        "list_name": "Hercule — Kinésithérapeutes (France)",
        "campaign_name": "Hercule — Kinésithérapeutes (France)",
        "calendly_url": "https://calendly.com/jum-advisory/rendez-vous-comptable-kinesitherapeute",
    },
    {
        "key": "avocat",
        "label": "Avocat",
        "segment": "avocat",
        "list_id": "d4993823-d593-4839-8d67-48aa32782998",
        "campaign_id": "273473f0-b2f1-4462-a668-f0277f90d807",
        "list_name": "Hercule — Avocats (France)",
        "campaign_name": "Hercule — Avocats (France)",
        "calendly_url": "https://calendly.com/jum-advisory/rendez-vous-comptable-avocat",
    },
    {
        "key": "architecte",
        "label": "Architecte DPLG",
        "segment": "architecte",
        "list_id": "44b49536-aa48-4acd-9d3b-117e331d41f3",
        "campaign_id": "7ec0e211-9832-4baf-8803-e12ab93ee517",
        "list_name": "Hercule — Architectes DPLG (France)",
        "campaign_name": "Hercule — Architectes DPLG (France)",
        "calendly_url": "https://calendly.com/jum-advisory/rendez-vous-comptable-architecte-dplg",
    },
    {
        "key": "veterinaire",
        "label": "Vétérinaire",
        "segment": "veterinaire",
        "list_id": "29a1ca36-9964-4ee8-bc20-7a8c840af21d",
        "campaign_id": "7300a1ce-9e55-4bfa-92fd-d25361a22a59",
        "list_name": "Hercule — Vétérinaires (France)",
        "campaign_name": "Hercule — Vétérinaires (France)",
        "calendly_url": "https://calendly.com/jum-advisory/rendez-vous-comptable-veterinaire",
    },
]

JUM_ADVISORY_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": JUM_VERTICALS[0]["list_id"],
    "INSTANTLY_CAMPAIGN_ID": JUM_VERTICALS[0]["campaign_id"],
    "INSTANTLY_SUBSEQUENCE_ID": "",
    "INSTANTLY_PUSH_EVERY": 100,
    "INSTANTLY_PROVISION_LINKS": True,
    "LINK_PROVISION_CATEGORY": "jum",
    "ENRICH_ENABLED": False,
    "PRESET_ID": PRESET_ID,
    "PRESET_LABEL": PRESET_LABEL,
    "JUM_VERTICALS": JUM_VERTICALS,
    "NICHE_METADATA": {
        "angle": "Outreach secrétaire comptable JUM — restaurants, terrassement/BTP, dentistes, médecins, kinés, avocats, architectes, vétérinaires",
        "segments": [
            "restaurant",
            "b2b",
            "dentiste",
            "medecin",
            "kine",
            "avocat",
            "architecte",
            "veterinaire",
        ],
        "verticals": [
            "restaurant",
            "btp",
            "dentiste",
            "medecin",
            "kine",
            "avocat",
            "architecte",
            "veterinaire",
        ],
        "signature": "Béatrice Meyer — Secrétaire Comptable JUM — jum-advisory.com",
    },
    "KEYWORDS": [
        "restaurant",
        "terrassement",
        "btp",
        "expert-comptable",
        "cabinet comptable",
        "chirurgien-dentiste",
        "kinésithérapeute",
        "avocat",
        "architecte",
        "vétérinaire",
        "dirigeant",
    ],
    "LOCATIONS": ["France"],
    "TARGET_LEADS": 500,
    "SERVICE_DEFAULT": "Expertise comptable JUM",
}

CONFIG = JUM_ADVISORY_CONFIG
