"""Niche taxonomy keyword lists for the standalone Instantly filter tool."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping


@dataclass(frozen=True)
class NicheTaxonomy:
    key: str
    included: tuple[str, ...]
    excluded: tuple[str, ...] = ()


# Canonical keys used in STATUS_FILTER / NICHE columns
NICHE_BTP = "BTP"
NICHE_RESTAURANT = "RESTAURANT"
NICHE_COMPTABLE = "COMPTABLE"
NICHE_CONSEIL_FINANCIER = "CONSEIL_FINANCIER"
NICHE_TERRASSEMENT = "TERRASSEMENT"
NICHE_DENTISTE = "DENTISTE"

NICHES: dict[str, NicheTaxonomy] = {
    NICHE_BTP: NicheTaxonomy(
        key=NICHE_BTP,
        included=(
            "entrepreneur en bâtiment",
            "société de construction",
            "entreprise de construction",
            "entreprise de bâtiment",
            "travaux de construction",
            "travaux publics",
            "artisan bâtiment",
            "artisan du bâtiment",
            "plombier",
            "électricien",
            "maçon",
            "carreleur",
            "peintre en bâtiment",
            "couvreur",
            "menuisier",
            "charpentier",
            "chauffagiste",
            "plaquiste",
            "façadier",
            "terrassier",
            "terrassement",
            "isolation thermique",
            "installateur de systèmes de chauffage",
            "constructeur de maisons",
            "rénovation",
            "btp",
            "génie civil",
            "gros œuvre",
            "second œuvre",
            # Common Google Maps trade variants seen in Instantly exports
            "carrelage",
            "isolation",
            "cheministe",
            "salle de bains",
            "travaux généraux",
            "revêtements de sol",
            "revêtement de sol",
            "plâtrier",
            "platrier",
            "serrurier",
            "pavage",
        ),
        excluded=(
            "magasin de matériaux",
            "négoce de matériaux",
            "grossiste en matériaux",
            "distributeur de matériaux",
            "fournisseur de matériaux",
            "magasin de carrelage",
            "quincaillerie",
            "point p",
            "école",
            "centre de formation",
            "organisme de formation",
            "bureau d'études",
            "cabinet d'ingénierie",
            "ingénierie du bâtiment",
            "cabinet d'architecture",
            "architecte",
            "maître d'œuvre",
            "promoteur immobilier",
            "agence immobilière",
            "agent immobilier",
            "expert immobilier",
            "constructeur immobilier",
            "location d'équipement",
            "location de matériel",
            "location d'engins",
            "location de nacelles",
            "syndicat",
            "association",
            "administration",
            "collectivité",
            "assurance construction",
            "garantie décennale",
        ),
    ),
    NICHE_RESTAURANT: NicheTaxonomy(
        key=NICHE_RESTAURANT,
        included=(
            "restaurant",
            "brasserie",
            "bistrot",
            "restauration",
            "french restaurant",
            "restaurant traditionnel",
            "restaurant français",
            "gastronomique",
        ),
        excluded=(
            "franchise",
            "dark kitchen",
            "logiciel de caisse",
            "logiciel restauration",
            "plateforme de livraison",
            "mcdonald",
            "kfc",
            "burger king",
        ),
    ),
    NICHE_COMPTABLE: NicheTaxonomy(
        key=NICHE_COMPTABLE,
        # Derived from ENRICH keywords — no TAXONOMY_* section on the preset.
        included=(
            "expert comptable",
            "expert-comptable",
            "expertise comptable",
            "comptabilité",
            "cabinet comptable",
            "comptables",
            "bilan",
            "liasse fiscale",
            "fiscalité",
            "commissaire aux comptes",
            "accounting",
            "accountant",
        ),
        excluded=(
            "dougs",
            "pennylane",
            "fiducial",
            "in extenso",
            "centre de gestion",
            "kpmg",
            "deloitte",
            "ernst & young",
            "ernst and young",
            "pricewaterhousecoopers",
            "logiciel comptable",
            "plateforme comptable",
            "recrutement",
            "chasseur de têtes",
            "gestion de patrimoine",
        ),
    ),
    NICHE_CONSEIL_FINANCIER: NicheTaxonomy(
        key=NICHE_CONSEIL_FINANCIER,
        included=(
            "conseiller financier",
            "financial consultant",
            "financial planner",
            "planificateur financier",
            "gestion de patrimoine",
            "gestionnaire de patrimoine",
            "conseiller en investissements financiers",
            "conseil en investissement",
            "courtier en placement financier",
            "investment service",
            "wealth management",
            "cgp",
            "cgpi",
            "cif",
            "intermédiaire en assurance",
            "courtier en assurance",
            "courtier d'assurances",
        ),
        excluded=(
            "crédit agricole",
            "bnp paribas",
            "société générale",
            "banque populaire",
            "caisse d'épargne",
            "axa",
            "fortuneo",
            "linxea",
            "mutuelle",
            "lcl",
            "boursorama",
            "bforbank",
            "banque",
            "bank",
            "restaurant",
            "école",
            "ecole",
            "business school",
            "université",
            "avocat",
            "notaire",
            "agence immobilière",
            "agence immobiliere",
            "immobilier",
            "real estate",
            "expert immobilier",
            "agent immobilier",
            "gestionnaire de patrimoine immobilier",
            "société de gestion immobilière",
            "hypothécaire",
            "mortgage",
            "courtier en prêts",
            "expert-comptable",
            "expert comptable",
            "expertise comptable",
            "comptable",
            "automobile",
            "auto broker",
            "garage",
            "agence d'assurance",
        ),
    ),
    NICHE_TERRASSEMENT: NicheTaxonomy(
        key=NICHE_TERRASSEMENT,
        included=(
            "terrassement",
            "terrassier",
            "entreprise de terrassement",
            "travaux de terrassement",
            "vrd",
            "voirie et réseaux divers",
            "voirie",
            "travaux publics",
            "réseaux humides",
            "réseaux secs",
            "canalisation",
            "assainissement",
            "égout",
            "adduction",
            "distribution d'eau",
            "gaz",
            "électricité réseau",
            "fibre optique",
            "télécom",
            "nivellement",
            "déblai",
            "remblai",
            "compactage",
            "drainage",
            "fondations spéciales",
            "enrobé",
            "chaussée",
            "tranchée",
            "forage horizontal",
            "forage dirigé",
            "entreprise de voirie",
            "entreprise d'assainissement",
            "entreprise de travaux publics",
            "génie civil",
        ),
        excluded=(
            "plombier",
            "électricien",
            "maçon",
            "carreleur",
            "peintre en bâtiment",
            "couvreur",
            "menuisier",
            "charpentier",
            "chauffagiste",
            "plaquiste",
            "façadier",
            "isolation thermique",
            "constructeur de maisons",
            "rénovation intérieure",
            "second œuvre",
            "magasin de matériaux",
            "négoce de matériaux",
            "grossiste en matériaux",
            "distributeur de matériaux",
            "fournisseur de matériaux",
            "quincaillerie",
            "point p",
            "location d'équipement",
            "location de matériel",
            "location d'engins",
            "location de nacelles",
            "bureau d'études",
            "cabinet d'ingénierie",
            "ingénierie du bâtiment",
            "cabinet d'architecture",
            "architecte",
            "maître d'œuvre",
            "promoteur immobilier",
            "agence immobilière",
            "agent immobilier",
            "école",
            "centre de formation",
            "organisme de formation",
            "syndicat",
            "association",
            "administration",
            "collectivité",
            "assurance construction",
            "garantie décennale",
        ),
    ),
    NICHE_DENTISTE: NicheTaxonomy(
        key=NICHE_DENTISTE,
        included=(
            "chirurgien-dentiste",
            "chirurgien dentiste",
            "cabinet dentaire",
            "dentiste",
            "soins dentaires",
            "orthodontie",
            "orthodontiste",
            "dental clinic",
            "dentist",
            "orthodontist",
            "implantologie",
            "dentiste pédiatrique",
            "chirurgie dentaire",
        ),
        excluded=(
            "logiciel dentaire",
            "recrutement",
            "laboratoire de prothèse",
            "prothésiste dentaire",
            "laboratoire dentaire",
            "mutuelle",
            "assurance",
            "centre mutualiste",
            "hôpital",
            "hopital",
        ),
    ),
}

# Raw Instantly Niche / Service / PRESET_LABEL strings → canonical niche key
NICHE_ALIASES: Mapping[str, str] = {
    # BTP
    "btp": NICHE_BTP,
    "btp pme": NICHE_BTP,
    "btp pme (france)": NICHE_BTP,
    "btp pme 3-15 salariés (france)": NICHE_BTP,
    "btp pme 3-15 salaries (france)": NICHE_BTP,
    "rénovation": NICHE_BTP,
    "renovation": NICHE_BTP,
    # Restaurant
    "restaurant": NICHE_RESTAURANT,
    "restaurants": NICHE_RESTAURANT,
    "restaurants indépendants": NICHE_RESTAURANT,
    "restaurants independants": NICHE_RESTAURANT,
    "restaurants indépendants (france)": NICHE_RESTAURANT,
    "restauration": NICHE_RESTAURANT,
    # Comptable
    "comptable": NICHE_COMPTABLE,
    "comptables": NICHE_COMPTABLE,
    "expertise comptable": NICHE_COMPTABLE,
    "cabinets expertise comptable": NICHE_COMPTABLE,
    "cabinets expertise comptable (france)": NICHE_COMPTABLE,
    "cabinets ec vol (outscraper taxonomy)": NICHE_COMPTABLE,
    "cabinets ec vol": NICHE_COMPTABLE,
    "expert comptable": NICHE_COMPTABLE,
    "expert-comptable": NICHE_COMPTABLE,
    # Conseil financier
    "conseil financier": NICHE_CONSEIL_FINANCIER,
    "conseiller financier": NICHE_CONSEIL_FINANCIER,
    "cabinets conseiller financier": NICHE_CONSEIL_FINANCIER,
    "cabinets conseiller financier (france)": NICHE_CONSEIL_FINANCIER,
    "gestion de patrimoine": NICHE_CONSEIL_FINANCIER,
    "conseillers gestion patrimoine": NICHE_CONSEIL_FINANCIER,
    "cgp": NICHE_CONSEIL_FINANCIER,
    "cgpi": NICHE_CONSEIL_FINANCIER,
    # Terrassement
    "terrassement": NICHE_TERRASSEMENT,
    "terrassement / vrd": NICHE_TERRASSEMENT,
    "terrassement / vrd (france)": NICHE_TERRASSEMENT,
    "vrd": NICHE_TERRASSEMENT,
    # Dentiste
    "dentiste": NICHE_DENTISTE,
    "dentistes": NICHE_DENTISTE,
    "chirurgien-dentiste": NICHE_DENTISTE,
    "chirurgiens-dentistes": NICHE_DENTISTE,
    "chirurgiens-dentistes (france)": NICHE_DENTISTE,
    "chirurgie dentaire": NICHE_DENTISTE,
    "cabinet dentaire": NICHE_DENTISTE,
    "orthodontiste": NICHE_DENTISTE,
}


def resolve_niche(raw: str | None) -> str | None:
    """Map a free-text niche/service label to a canonical niche key, or None."""
    if not raw:
        return None
    key = str(raw).strip().lower()
    if not key:
        return None
    if key in NICHE_ALIASES:
        return NICHE_ALIASES[key]
    # Partial contains match (longest alias first to avoid short false positives)
    for alias, niche in sorted(NICHE_ALIASES.items(), key=lambda item: -len(item[0])):
        if alias in key:
            return niche
    # Exact canonical keys
    upper = key.upper().replace(" ", "_")
    if upper in NICHES:
        return upper
    return None
