-- Payment onboarding nurture sequence (DEC · CIF · IAS) — 9 steps post-Stripe

ALTER TABLE public.booking_email_jobs
  DROP CONSTRAINT IF EXISTS booking_email_jobs_email_type_check;

ALTER TABLE public.booking_email_jobs
  ADD CONSTRAINT booking_email_jobs_email_type_check
  CHECK (email_type IN (
    'immediate',
    'h48_confirm',
    'h24_relance',
    'h20_cancel',
    'role_seq_48',
    'role_seq_24',
    'product_calendly_welcome',
    'product_calendly_reminder',
    'product_payment_welcome',
    'upsell_email_1',
    'upsell_email_2',
    'upsell_email_3',
    'close_indecis_1',
    'close_indecis_2',
    'close_indecis_3',
    'no_show_indecis_1',
    'no_show_indecis_2',
    'no_show_indecis_3',
    'onboarding_retraction_hold',
    'onboarding_j0',
    'onboarding_j0_bis',
    'onboarding_j1',
    'onboarding_reminder_m10',
    'onboarding_reminder_m5',
    'onboarding_reminder_p5',
    'deliverance_search_started',
    'deliverance_d7_update',
    'deliverance_milestone',
    'deliverance_waitlist',
    'match_proposal',
    'match_proposal_followup',
    'match_booking_agence',
    'survey_rdv_entreprise',
    'survey_rdv_entreprise_followup',
    'survey_rdv_agence',
    'survey_rdv_agence_followup',
    'sold_check_j7',
    'payment_notification_client',
    'modalites_ask',
    'modalites_cancel',
    'modalites_enforce_cancel',
    'comptable_acquisition_welcome',
    'comptable_acquisition_config_ready',
    'comptable_acquisition_rdv_reminder',
    'comptable_acquisition_rdv_final',
    'proposition_ludovic_welcome',
    'proposition_ludovic_config_ready',
    'proposition_ludovic_rdv_reminder',
    'proposition_ludovic_rdv_final',
    'conference_invite',
    'conference_invite_24',
    'conference_invite_48',
    'conference_invite_72',
    'free_trial_1',
    'free_trial_2',
    'free_trial_3',
    'free_trial_started_1',
    'free_trial_started_2',
    'free_trial_started_3',
    'payment_onboarding_1',
    'payment_onboarding_2',
    'payment_onboarding_3',
    'payment_onboarding_4',
    'payment_onboarding_5',
    'payment_onboarding_6',
    'payment_onboarding_7',
    'payment_onboarding_8',
    'payment_onboarding_9'
  ));

ALTER TABLE public.booking_email_templates
  DROP CONSTRAINT IF EXISTS booking_email_templates_email_type_check;

ALTER TABLE public.booking_email_templates
  ADD CONSTRAINT booking_email_templates_email_type_check
  CHECK (email_type IN (
    'immediate',
    'h48_confirm',
    'h24_relance',
    'h20_cancel',
    'role_seq_48',
    'role_seq_24',
    'product_calendly_welcome',
    'product_calendly_reminder',
    'product_payment_welcome',
    'upsell_email_1',
    'upsell_email_2',
    'upsell_email_3',
    'close_indecis_1',
    'close_indecis_2',
    'close_indecis_3',
    'no_show_indecis_1',
    'no_show_indecis_2',
    'no_show_indecis_3',
    'onboarding_retraction_hold',
    'onboarding_j0',
    'onboarding_j0_bis',
    'onboarding_j1',
    'onboarding_reminder_m10',
    'onboarding_reminder_m5',
    'onboarding_reminder_p5',
    'deliverance_search_started',
    'deliverance_d7_update',
    'deliverance_milestone',
    'deliverance_waitlist',
    'match_proposal',
    'match_proposal_followup',
    'match_booking_agence',
    'survey_rdv_entreprise',
    'survey_rdv_entreprise_followup',
    'survey_rdv_agence',
    'survey_rdv_agence_followup',
    'sold_check_j7',
    'payment_notification_client',
    'modalites_ask',
    'modalites_cancel',
    'modalites_enforce_cancel',
    'comptable_acquisition_welcome',
    'comptable_acquisition_config_ready',
    'comptable_acquisition_rdv_reminder',
    'comptable_acquisition_rdv_final',
    'proposition_ludovic_welcome',
    'proposition_ludovic_config_ready',
    'proposition_ludovic_rdv_reminder',
    'proposition_ludovic_rdv_final',
    'conference_invite',
    'conference_invite_24',
    'conference_invite_48',
    'conference_invite_72',
    'free_trial_1',
    'free_trial_2',
    'free_trial_3',
    'free_trial_started_1',
    'free_trial_started_2',
    'free_trial_started_3',
    'payment_onboarding_1',
    'payment_onboarding_2',
    'payment_onboarding_3',
    'payment_onboarding_4',
    'payment_onboarding_5',
    'payment_onboarding_6',
    'payment_onboarding_7',
    'payment_onboarding_8',
    'payment_onboarding_9'
  ));

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'booking_email_jobs_triggered_by_check'
  ) THEN
    ALTER TABLE public.booking_email_jobs
      DROP CONSTRAINT booking_email_jobs_triggered_by_check;
  END IF;
END $$;

ALTER TABLE public.booking_email_jobs
  ADD CONSTRAINT booking_email_jobs_triggered_by_check
  CHECK (triggered_by IN (
    'calendly',
    'manual',
    'retry',
    'role_recovery',
    'stripe_payment',
    'calendly_seat_cron',
    'onboarding_complete',
    'sales_call_completed',
    'sales_call_not_paid',
    'sales_call_no_show',
    'onboarding_sequence',
    'admin_match',
    'calendly_match_booking',
    'cron_rdv_survey',
    'cron_sold_check',
    'stripe_payment_notification',
    'deliverance_admin',
    'admin_complete_appt',
    'admin_modalites',
    'comptable_acquisition_sequence',
    'proposition_ludovic_sequence',
    'cif_conference_sequence',
    'free_trial_sequence',
    'free_trial_started_sequence',
    'payment_onboarding_sequence'
  ));
