"""BTP Second Œuvre & Rénovation scraper preset — static rules; secrets come from config_loader."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "btp_reno"
PRESET_LABEL = "BTP Second Œuvre & Rénovation"

_LIST_ID = "4cb53db3-b323-4dba-bd82-152f486ecd2c"
_CAMPAIGN_ID = "7fc142be-ac42-4527-8b4d-8877752d8d7f"

BTP_RENO_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [_LIST_ID] if _LIST_ID else [],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [_CAMPAIGN_ID] if _CAMPAIGN_ID else [],
    "INSTANTLY_PUSH_EVERY": 100,
    "ENRICH_ENABLED": True,
    "ENRICH_BATCH_SIZE": 50,
    "ENRICH_CONCURRENCY": 20,
    "ENRICH_TIMEOUT_MS": 10000,
    "ENRICH_INCLUDED_KEYWORDS": [
        "pompe à chaleur",
        "isolation thermique",
        "rénovation énergétique",
        "rénovation globale",
        "menuiserie industrielle",
        "ITE",
        "ITE isolation",
        "installateur CVC",
        "chauffage",
        "climatisation",
        "fenêtres",
        "menuiserie extérieure",
        "promoteur régional",
        "MaPrimeRénov",
        "BBC",
        "RE2020",
        "audit énergétique",
        "second œuvre",
    ],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [
        "bricolage",
        "particulier",
        "auto-entrepreneur",
        "agence immobilière",
        "architecte d'intérieur",
        "décoration",
        "quincaillerie",
        "grande surface",
    ],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [
        "formation BTP",
        "logiciel BTP",
        "location matériel",
        "négoce matériaux",
    ],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 6,
    "OUTSCRAPER_LIMIT_PER_QUERY": 30,
    "OUTSCRAPER_POLL_INITIAL_S": 45,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 600,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 8,
    "TARGET_LEADS": 5_000,
    "TARGET_MODE": "instantly_pushed",
    "SERVICE_DEFAULT": "Rénovation énergétique",
    "SERVICE_RULES": [
        {"label": "Pompe à chaleur", "keywords": ["pompe à chaleur", "PAC", "installateur CVC", "climatisation"]},
        {"label": "Isolation", "keywords": ["isolation thermique", "ITE", "ITE isolation", "isolation"]},
        {"label": "Menuiserie", "keywords": ["menuiserie industrielle", "menuiserie extérieure", "fenêtres"]},
        {"label": "Rénovation globale", "keywords": ["rénovation globale", "rénovation énergétique", "MaPrimeRénov", "audit énergétique"]},
        {"label": "Promotion immobilière", "keywords": ["promoteur régional", "promotion immobilière"]},
    ],
    "KEYWORDS": [
        "installateur pompe à chaleur",
        "isolation thermique",
        "menuiserie industrielle",
        "rénovation globale",
        "promoteur régional",
        "rénovation énergétique",
        "entreprise isolation ITE",
        "installateur CVC",
        "menuiserie extérieure",
        "entreprise second œuvre",
        "chauffagiste professionnel",
        "fenêtres industrielles",
    ],
    "EXPANSION_KEYWORDS": [
        "PAC air eau",
        "MaPrimeRénov entreprise",
        "audit énergétique",
        "ITE façade",
        "promoteur immobilier régional",
        "rénovation BBC",
        "installateur climatisation",
        "menuiserie aluminium",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": True,
    "PAPPERS_MIN_EMPLOYEES": 10,
    "PAPPERS_ON_UNKNOWN": "reject",
    "PAPPERS_CONCURRENCY": 5,
    "PAPPERS_NAF_PREFIXES": [
        "41.10",
        "41.20",
        "43.21",
        "43.22",
        "43.29",
        "43.32",
        "43.33",
        "43.91",
        "43.99",
        "33.20",
    ],
    "NICHE_METADATA": {
        "angle": "Génération de leads qualifiés (Google Ads / Meta Ads), refonte web conversion, e-réputation / avis clients.",
        "valeur_client": "10 000 € à 30 000 €",
        "effectif_cible": "10 à 50+ salariés",
    },
}

CONFIG = BTP_RENO_CONFIG
