"""Cliniques Vétérinaires & Médical Privé scraper preset — static rules; secrets come from config_loader."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "cliniques_medical"
PRESET_LABEL = "Cliniques Vétérinaires & Médical Privé"

_LIST_ID = "f98cb5fc-811e-4bdb-8c84-5b3d77824043"
_CAMPAIGN_ID = "f26cd240-be44-4dad-81d4-ebd4dcb94689"

CLINIQUES_MEDICAL_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [_LIST_ID] if _LIST_ID else [],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [_CAMPAIGN_ID] if _CAMPAIGN_ID else [],
    "INSTANTLY_PUSH_EVERY": 100,
    "ENRICH_ENABLED": True,
    "ENRICH_BATCH_SIZE": 50,
    "ENRICH_CONCURRENCY": 20,
    "ENRICH_TIMEOUT_MS": 10000,
    "ENRICH_INCLUDED_KEYWORDS": [
        "groupe vétérinaire",
        "clinique vétérinaire",
        "centre d'imagerie",
        "imagerie médicale",
        "clinique dentaire",
        "pôle de santé",
        "cabinet multi-sites",
        "hôpital vétérinaire",
        "centre dentaire",
        "scanner",
        "IRM",
        "chirurgie",
        "praticiens",
    ],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [
        "toilettage",
        "animalerie",
        "refuge",
        "SPA",
        "mutuelle",
        "assurance santé",
        "laboratoire pharmaceutique",
        "pharmacie",
        "auto-entrepreneur",
    ],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [
        "formation vétérinaire",
        "école vétérinaire",
        "fournitures médicales",
        "logiciel cabinet",
    ],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 6,
    "OUTSCRAPER_LIMIT_PER_QUERY": 30,
    "OUTSCRAPER_POLL_INITIAL_S": 45,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 600,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 8,
    "TARGET_LEADS": 5_000,
    "TARGET_MODE": "instantly_pushed",
    "SERVICE_DEFAULT": "Santé privée",
    "SERVICE_RULES": [
        {"label": "Vétérinaire", "keywords": ["groupe vétérinaire", "clinique vétérinaire", "hôpital vétérinaire"]},
        {"label": "Imagerie médicale", "keywords": ["centre d'imagerie", "imagerie médicale", "scanner", "IRM"]},
        {"label": "Dentaire", "keywords": ["clinique dentaire", "centre dentaire"]},
        {"label": "Pôle de santé", "keywords": ["pôle de santé", "cabinet multi-sites", "maison de santé"]},
    ],
    "KEYWORDS": [
        "groupe vétérinaire",
        "centre d'imagerie médicale",
        "clinique dentaire",
        "pôle de santé privé",
        "cabinet multi-sites",
        "clinique vétérinaire",
        "hôpital vétérinaire",
        "centre dentaire",
        "imagerie médicale",
        "maison de santé pluridisciplinaire",
        "clinique privée",
        "centre de santé",
    ],
    "EXPANSION_KEYWORDS": [
        "réseau vétérinaire",
        "centre IRM",
        "cabinet dentaire groupe",
        "pôle médical privé",
        "clinique animalière",
        "imagerie diagnostique",
        "centre de chirurgie dentaire",
        "MSP pluriprofessionnelle",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": True,
    "PAPPERS_MIN_EMPLOYEES": 10,
    "PAPPERS_ON_UNKNOWN": "reject",
    "PAPPERS_CONCURRENCY": 5,
    "PAPPERS_NAF_PREFIXES": [
        "75.00",
        "86.10",
        "86.21",
        "86.22",
        "86.23",
        "86.90",
    ],
    "NICHE_METADATA": {
        "angle": "SEO local, marque employeur (recrutement praticiens), portail client / app mobile, community management.",
        "valeur_client": "",
        "effectif_cible": "8 à 30 salariés (seuil scraper >= 10)",
    },
}

CONFIG = CLINIQUES_MEDICAL_CONFIG
