"""Expertise Comptable & Conseil scraper preset — static rules; secrets come from config_loader."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "expertise_conseil"
PRESET_LABEL = "Expertise Comptable & Conseil"

_LIST_ID = "5170998d-da9b-4992-9628-bf5bc5b4edbf"
_CAMPAIGN_ID = "fd0175d2-1d13-4616-b1b8-cc498b41e65d"

EXPERTISE_CONSEIL_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [_LIST_ID] if _LIST_ID else [],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [_CAMPAIGN_ID] if _CAMPAIGN_ID else [],
    "INSTANTLY_PUSH_EVERY": 100,
    "ENRICH_ENABLED": True,
    "ENRICH_BATCH_SIZE": 50,
    "ENRICH_CONCURRENCY": 20,
    "ENRICH_TIMEOUT_MS": 10000,
    "ENRICH_INCLUDED_KEYWORDS": [
        "expertise comptable",
        "expert-comptable",
        "conseil de gestion",
        "conseil en gestion",
        "gestion de patrimoine B2B",
        "audit financier",
        "commissaire aux comptes",
        "cabinet comptable",
        "social et fiscal",
        "liasse fiscale",
        "paie",
        "bilan",
        "fiduciaire",
    ],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [
        "logiciel comptable",
        "agence immobilière",
        "notaire",
        "avocat",
        "assurance auto",
        "auto-entrepreneur",
        "centre de formation",
        "agence de communication",
    ],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [
        "ERP",
        "Sage",
        "Cegid",
        "banque",
        "crédit consommation",
        "stage comptabilité",
    ],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 6,
    "OUTSCRAPER_LIMIT_PER_QUERY": 30,
    "OUTSCRAPER_POLL_INITIAL_S": 45,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 600,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 8,
    "TARGET_LEADS": 5_000,
    "TARGET_MODE": "instantly_pushed",
    "SERVICE_DEFAULT": "Expertise comptable",
    "SERVICE_RULES": [
        {"label": "Expertise comptable", "keywords": ["expertise comptable", "expert-comptable", "cabinet comptable", "fiduciaire"]},
        {"label": "Conseil de gestion", "keywords": ["conseil de gestion", "conseil en gestion", "pilotage"]},
        {"label": "Audit", "keywords": ["audit financier", "commissaire aux comptes", "audit"]},
        {"label": "Patrimoine B2B", "keywords": ["gestion de patrimoine B2B", "patrimoine professionnel"]},
    ],
    "KEYWORDS": [
        "cabinet d'expertise comptable",
        "conseil de gestion",
        "gestion de patrimoine B2B",
        "audit financier régional",
        "expert-comptable",
        "cabinet comptable",
        "commissaire aux comptes",
        "fiduciaire",
        "conseil en gestion",
        "expertise comptable PME",
        "cabinet social et fiscal",
        "audit légal",
    ],
    "EXPANSION_KEYWORDS": [
        "ECG",
        "Cerfrance",
        "commissariat aux comptes",
        "externalisation comptable",
        "conseil juridique fiscal",
        "gestion paie",
        "expert-comptable groupe",
        "réseau comptable régional",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": True,
    "PAPPERS_MIN_EMPLOYEES": 10,
    "PAPPERS_ON_UNKNOWN": "reject",
    "PAPPERS_CONCURRENCY": 5,
    "PAPPERS_NAF_PREFIXES": [
        "66.30",
        "69.10",
        "69.20",
        "70.22",
    ],
    "NICHE_METADATA": {
        "angle": "Inbound marketing, organisation de webinaires, livres blancs, refonte d'image / positionnement haut de gamme.",
        "valeur_client": "",
        "effectif_cible": "10 à 40 collaborateurs",
    },
}

CONFIG = EXPERTISE_CONSEIL_CONFIG
