"""Formation, Écoles Privées & CFA scraper preset — static rules; secrets come from config_loader."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "formation_cfa"
PRESET_LABEL = "Formation, Écoles Privées & CFA"

_LIST_ID = "533e3686-08ef-4c30-b961-de635af85643"
_CAMPAIGN_ID = "117e193e-50ea-4f95-9a12-f7f5529e1156"

FORMATION_CFA_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [_LIST_ID] if _LIST_ID else [],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [_CAMPAIGN_ID] if _CAMPAIGN_ID else [],
    "INSTANTLY_PUSH_EVERY": 100,
    "ENRICH_ENABLED": True,
    "ENRICH_BATCH_SIZE": 50,
    "ENRICH_CONCURRENCY": 20,
    "ENRICH_TIMEOUT_MS": 10000,
    "ENRICH_INCLUDED_KEYWORDS": [
        "centre de formation",
        "formation continue",
        "école supérieure",
        "école privée",
        "CFA",
        "organisme de formation",
        "apprentissage",
        "alternance",
        "Qualiopi",
        "OPCO",
        "RNCP",
        "titre professionnel",
        "JPO",
        "formation B2B",
    ],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [
        "auto-école",
        "soutien scolaire",
        "cours particuliers",
        "e-learning freelance",
        "MOOC gratuit",
        "université publique",
        "éducation nationale",
    ],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [
        "logiciel LMS",
        "plateforme e-learning",
        "éditeur de contenus",
        "recrutement formateurs",
    ],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 6,
    "OUTSCRAPER_LIMIT_PER_QUERY": 30,
    "OUTSCRAPER_POLL_INITIAL_S": 45,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 600,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 8,
    "TARGET_LEADS": 5_000,
    "TARGET_MODE": "instantly_pushed",
    "SERVICE_DEFAULT": "Organisme de formation",
    "SERVICE_RULES": [
        {"label": "Formation continue", "keywords": ["centre de formation", "formation continue", "organisme de formation", "Qualiopi"]},
        {"label": "École privée", "keywords": ["école supérieure", "école privée", "RNCP"]},
        {"label": "CFA", "keywords": ["CFA", "apprentissage", "alternance"]},
        {"label": "Formation B2B", "keywords": ["formation B2B", "formation professionnelle", "OPCO"]},
    ],
    "KEYWORDS": [
        "centre de formation continue",
        "école supérieure privée",
        "CFA régional",
        "organisme de formation B2B",
        "organisme de formation",
        "école privée",
        "centre de formation professionnelle",
        "CFA apprentissage",
        "formation continue entreprise",
        "école de commerce privée",
        "organisme Qualiopi",
        "formation en alternance",
    ],
    "EXPANSION_KEYWORDS": [
        "OF Qualiopi",
        "titre RNCP",
        "JPO école",
        "formation professionnelle continue",
        "CFA d'entreprise",
        "école d'ingénieurs privée",
        "organisme OPCO",
        "campus privé",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": True,
    "PAPPERS_MIN_EMPLOYEES": 10,
    "PAPPERS_ON_UNKNOWN": "reject",
    "PAPPERS_CONCURRENCY": 5,
    "PAPPERS_NAF_PREFIXES": [
        "85.31",
        "85.32",
        "85.41",
        "85.42",
        "85.59",
    ],
    "NICHE_METADATA": {
        "angle": "Acquisition continue (Social/Google Ads), automatisation e-mailing / Nurturing, événements / JPO virtuelles.",
        "valeur_client": "",
        "effectif_cible": "10 à 50 salariés + vacataires",
    },
}

CONFIG = FORMATION_CFA_CONFIG
