"""PME B2B & Industrie scraper preset — static rules; secrets come from config_loader."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "pme_industrie"
PRESET_LABEL = "PME B2B & Industrie"

_LIST_ID = "d6b95e96-0e79-4aa1-948a-89916f7f8586"
_CAMPAIGN_ID = "42ef0c03-05ee-488d-81de-7eb75d023982"

PME_INDUSTRIE_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [_LIST_ID] if _LIST_ID else [],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [_CAMPAIGN_ID] if _CAMPAIGN_ID else [],
    "INSTANTLY_PUSH_EVERY": 100,
    "ENRICH_ENABLED": True,
    "ENRICH_BATCH_SIZE": 50,
    "ENRICH_CONCURRENCY": 20,
    "ENRICH_TIMEOUT_MS": 10000,
    "ENRICH_INCLUDED_KEYWORDS": [
        "équipements industriels",
        "sous-traitance aéronautique",
        "matériel médical",
        "usinage",
        "packaging industriel",
        "mécanique de précision",
        "fabrication",
        "atelier",
        "CNC",
        "tôlerie",
        "outillage",
        "industrie",
        "B2B",
        "sous-traitance industrielle",
    ],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [
        "grande distribution",
        "e-commerce grand public",
        "auto-entrepreneur",
        "artisan",
        "réparation automobile",
        "garage",
        "bricolage",
    ],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [
        "formation industrielle",
        "logiciel ERP",
        "intérim",
        "recrutement industrie",
    ],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 6,
    "OUTSCRAPER_LIMIT_PER_QUERY": 30,
    "OUTSCRAPER_POLL_INITIAL_S": 45,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 600,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 8,
    "TARGET_LEADS": 5_000,
    "TARGET_MODE": "instantly_pushed",
    "SERVICE_DEFAULT": "Industrie spécialisée",
    "SERVICE_RULES": [
        {"label": "Aéronautique", "keywords": ["sous-traitance aéronautique", "aéronautique", "spatial"]},
        {"label": "Matériel médical", "keywords": ["matériel médical", "dispositif médical", "médico-chirurgical"]},
        {"label": "Usinage", "keywords": ["usinage", "CNC", "mécanique de précision", "tôlerie"]},
        {"label": "Packaging", "keywords": ["packaging industriel", "emballage industriel"]},
        {"label": "Équipements", "keywords": ["équipements industriels", "machines industrielles", "outillage"]},
    ],
    "KEYWORDS": [
        "équipements industriels",
        "sous-traitance aéronautique",
        "matériel médical",
        "usinage",
        "packaging industriel",
        "mécanique de précision",
        "sous-traitance industrielle",
        "tôlerie industrielle",
        "machines-outils",
        "fabrication métallique",
        "dispositif médical fabricant",
        "emballage industriel",
    ],
    "EXPANSION_KEYWORDS": [
        "atelier CNC",
        "chaudronnerie industrielle",
        "outillage de précision",
        "équipementier industriel",
        "sous-traitant aéronautique",
        "emballage B2B",
        "usinage 5 axes",
        "industrie agroalimentaire équipement",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": True,
    "PAPPERS_MIN_EMPLOYEES": 10,
    "PAPPERS_ON_UNKNOWN": "reject",
    "PAPPERS_CONCURRENCY": 5,
    "PAPPERS_NAF_PREFIXES": [
        "22.22",
        "25.",
        "25.62",
        "27.",
        "28.",
        "30.30",
        "32.50",
        "33.12",
        "33.20",
    ],
    "NICHE_METADATA": {
        "angle": "Refonte vitrine haut de gamme, Inbound marketing, Social Selling LinkedIn, supports salons B2B.",
        "valeur_client": "Contrats jusqu'à plusieurs centaines de k€",
        "effectif_cible": "15 à 100+ salariés",
    },
}

CONFIG = PME_INDUSTRIE_CONFIG
