"""Services aux Bâtiments (FM) scraper preset — static rules; secrets come from config_loader."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "services_fm"
PRESET_LABEL = "Services aux Bâtiments (FM)"

_LIST_ID = "29119a30-89fb-457c-a723-583a7ddc98bd"
_CAMPAIGN_ID = "795ece57-2304-4629-ade3-4e1af7fc6c66"

SERVICES_FM_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [_LIST_ID] if _LIST_ID else [],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [_CAMPAIGN_ID] if _CAMPAIGN_ID else [],
    "INSTANTLY_PUSH_EVERY": 100,
    "ENRICH_ENABLED": True,
    "ENRICH_BATCH_SIZE": 50,
    "ENRICH_CONCURRENCY": 20,
    "ENRICH_TIMEOUT_MS": 10000,
    "ENRICH_INCLUDED_KEYWORDS": [
        "nettoyage tertiaire",
        "propreté",
        "gardiennage",
        "sécurité privée",
        "espaces verts",
        "facility management",
        "facilities management",
        "multiservices",
        "entretien locaux",
        "agent de sécurité",
        "surveillance",
        "maintenance immobilière",
        "services aux bâtiments",
    ],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [
        "ménage à domicile",
        "particulier",
        "auto-entrepreneur",
        "nounou",
        "aide à domicile",
        "paysagiste particulier",
        "jardinier amateur",
    ],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [
        "matériel de nettoyage",
        "vente produits d'entretien",
        "formation sécurité",
        "recrutement agents",
    ],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 6,
    "OUTSCRAPER_LIMIT_PER_QUERY": 30,
    "OUTSCRAPER_POLL_INITIAL_S": 45,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 600,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 8,
    "TARGET_LEADS": 5_000,
    "TARGET_MODE": "instantly_pushed",
    "SERVICE_DEFAULT": "Facility management",
    "SERVICE_RULES": [
        {"label": "Propreté", "keywords": ["nettoyage tertiaire", "propreté", "entretien locaux"]},
        {"label": "Sécurité", "keywords": ["gardiennage", "sécurité privée", "agent de sécurité", "surveillance"]},
        {"label": "Espaces verts", "keywords": ["espaces verts", "entretien espaces verts"]},
        {"label": "Facility management", "keywords": ["facility management", "facilities management", "multiservices", "services aux bâtiments"]},
    ],
    "KEYWORDS": [
        "nettoyage tertiaire",
        "gardiennage sécurité privée",
        "entretien espaces verts B2B",
        "facility management",
        "entreprise de propreté",
        "société de sécurité privée",
        "multiservices bâtiments",
        "nettoyage bureaux",
        "agent de sécurité",
        "espaces verts entreprises",
        "facilities management",
        "services généraux immeuble",
    ],
    "EXPANSION_KEYWORDS": [
        "propreté tertiaire",
        "surveillance humaine",
        "paysagiste entreprises",
        "maintenance immobilière",
        "FM multiservices",
        "nettoyage industriel",
        "SSIAP",
        "prestataire services généraux",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": True,
    "PAPPERS_MIN_EMPLOYEES": 10,
    "PAPPERS_ON_UNKNOWN": "reject",
    "PAPPERS_CONCURRENCY": 5,
    "PAPPERS_NAF_PREFIXES": [
        "80.10",
        "80.20",
        "81.10",
        "81.21",
        "81.22",
        "81.30",
    ],
    "NICHE_METADATA": {
        "angle": "Prospection B2B ciblée, supports commerciaux imprimés/digitaux, Google Ads B2B, marque employeur terrain.",
        "valeur_client": "",
        "effectif_cible": "30 à 150 salariés",
    },
}

CONFIG = SERVICES_FM_CONFIG
