"""Transport, Logistique & Déménagement B2B scraper preset — static rules; secrets come from config_loader."""

from french_cities import FRENCH_EXPANSION_LOCATIONS, FRENCH_LOCATIONS

PRESET_ID = "transport_logistique"
PRESET_LABEL = "Transport, Logistique & Déménagement B2B"

_LIST_ID = "e803f27d-db8a-40b1-8b8a-285d3cfe7d23"
_CAMPAIGN_ID = "9be7c634-7961-460a-b13a-4f5f0590e569"

TRANSPORT_LOGISTIQUE_CONFIG = {
    "OUTSCRAPER_API_KEY": "",
    "INSTANTLY_API_KEY": "",
    "INSTANTLY_LIST_ID": _LIST_ID,
    "INSTANTLY_CAMPAIGN_ID": _CAMPAIGN_ID,
    "INSTANTLY_DEDUP_LIST_IDS": [_LIST_ID] if _LIST_ID else [],
    "INSTANTLY_DEDUP_CAMPAIGN_IDS": [_CAMPAIGN_ID] if _CAMPAIGN_ID else [],
    "INSTANTLY_PUSH_EVERY": 100,
    "ENRICH_ENABLED": True,
    "ENRICH_BATCH_SIZE": 50,
    "ENRICH_CONCURRENCY": 20,
    "ENRICH_TIMEOUT_MS": 10000,
    "ENRICH_INCLUDED_KEYWORDS": [
        "transport routier",
        "logistique régionale",
        "transfert industriel",
        "déménagement d'entreprises",
        "déménagement entreprise",
        "flotte",
        "messagerie",
        "entreposage",
        "commissionnaire de transport",
        "affrètement",
        "livraison B2B",
        "supply chain",
        "entrepôt",
    ],
    "ENRICH_HARD_EXCLUDED_KEYWORDS": [
        "VTC",
        "taxi",
        "livraison de repas",
        "coursier vélo",
        "déménagement particulier uniquement",
        "auto-entrepreneur",
        "location voiture",
    ],
    "ENRICH_SOFT_EXCLUDED_KEYWORDS": [
        "formation transport",
        "logiciel TMS",
        "annonces d'emploi",
        "comparateur déménagement",
    ],
    "OUTSCRAPER_BATCH_SIZE": 200,
    "OUTSCRAPER_CONCURRENCY": 6,
    "OUTSCRAPER_LIMIT_PER_QUERY": 30,
    "OUTSCRAPER_POLL_INITIAL_S": 45,
    "OUTSCRAPER_POLL_INTERVAL_S": 5,
    "OUTSCRAPER_POLL_SLOW_S": 10,
    "OUTSCRAPER_POLL_TIMEOUT_S": 600,
    "OUTSCRAPER_TOTAL_LIMIT_BUFFER": 8,
    "TARGET_LEADS": 5_000,
    "TARGET_MODE": "instantly_pushed",
    "SERVICE_DEFAULT": "Transport & logistique",
    "SERVICE_RULES": [
        {"label": "Transport routier", "keywords": ["transport routier", "flotte", "affrètement", "messagerie"]},
        {"label": "Logistique", "keywords": ["logistique régionale", "entreposage", "entrepôt", "supply chain"]},
        {"label": "Transfert industriel", "keywords": ["transfert industriel", "manutention industrielle"]},
        {"label": "Déménagement B2B", "keywords": ["déménagement d'entreprises", "déménagement entreprise"]},
    ],
    "KEYWORDS": [
        "flotte transport routier",
        "logistique régionale",
        "transfert industriel",
        "déménagement d'entreprises",
        "transporteur routier",
        "commissionnaire de transport",
        "entreposage logistique",
        "déménagement entreprise",
        "messagerie palettes",
        "affréteur régional",
        "logistique B2B",
        "transport marchandises",
    ],
    "EXPANSION_KEYWORDS": [
        "transporteur PL",
        "groupage régional",
        "manutention industrielle",
        "déménageur professionnel",
        "entrepôt logistique",
        "livraison B2B",
        "transport frigorifique",
        "prestataire 3PL",
    ],
    "LOCATIONS": FRENCH_LOCATIONS,
    "EXPANSION_LOCATIONS": FRENCH_EXPANSION_LOCATIONS,
    "EXCLUDE_DOMAINS": [
        "duckduckgo.com",
        "google.com",
        "google.fr",
        "facebook.com",
        "instagram.com",
        "linkedin.com",
        "youtube.com",
        "pinterest.com",
        "tiktok.com",
        "societe.com",
        "pagesjaunes.fr",
    ],
    "PAPPERS_ENABLED": True,
    "PAPPERS_MIN_EMPLOYEES": 10,
    "PAPPERS_ON_UNKNOWN": "reject",
    "PAPPERS_CONCURRENCY": 20,
    "PAPPERS_NAF_PREFIXES": [
        "49.39",
        "49.41",
        "49.42",
        "52.10",
        "52.29",
    ],
    "NICHE_METADATA": {
        "angle": "Acquisition prospects B2B, SEA géolocalisé, vidéo institutionnelle de preuve de capacité.",
        "valeur_client": "",
        "effectif_cible": "20 à 100+ salariés",
    },
}

CONFIG = TRANSPORT_LOGISTIQUE_CONFIG
